const wordsDatabase = [
    { word: "Búho", hint: "Pregunta" },
    { word: "Tiburón", hint: "Sombra" },
    { word: "Elefante", hint: "Memoria" },
    { word: "Perro", hint: "Rutina" },
    { word: "Gato", hint: "Independencia" },
    { word: "León", hint: "Corona" },
    { word: "Águila", hint: "Perspectiva" },
    { word: "Delfín", hint: "Inteligencia" },
    { word: "Mariposa", hint: "Transformación" },
    { word: "Serpiente", hint: "Renovación" },
    { word: "Lobo", hint: "Manada" },
    { word: "Ballena", hint: "Profundidad" },
    { word: "Colibrí", hint: "Velocidad" },
    { word: "Oso", hint: "Hibernación" },
    { word: "Conejo", hint: "Fertilidad" },
    { word: "Tortuga", hint: "Paciencia" },
    { word: "Zorro", hint: "Astucia" },
    { word: "Pingüino", hint: "Fidelidad" },
    { word: "Camello", hint: "Resistencia" },
    { word: "Jirafa", hint: "Altura" },
    { word: "Canguro", hint: "Bolsillo" },
    { word: "Koala", hint: "Pereza" },
    { word: "Panda", hint: "Rareza" },
    { word: "Flamenco", hint: "Equilibrio" },
    { word: "Pulpo", hint: "Flexibilidad" },
    { word: "Cebra", hint: "Dualidad" },
    { word: "Hipopótamo", hint: "Sumergir" },
    { word: "Rinoceronte", hint: "Armadura" },
    { word: "Murciélago", hint: "Ecolocalización" },
    { word: "Hormiga", hint: "Colaboración" },
    { word: "Abeja", hint: "Organización" },
    { word: "Araña", hint: "Red" },
    { word: "Escorpión", hint: "Veneno" },
    { word: "Caracol", hint: "Lentitud" },
    { word: "Medusa", hint: "Transparencia" },
    { word: "Cangrejo", hint: "Lateral" },
    { word: "Pez dorado", hint: "Recuerdo" },
    { word: "Pavo real", hint: "Vanidad" },
    { word: "Cisne", hint: "Elegancia" },
    { word: "Cuervo", hint: "Presagio" },
    { word: "Loro", hint: "Repetición" },
    { word: "Gaviota", hint: "Libertad" },
    { word: "Murciélago", hint: "Noctámbulo" },
    { word: "Camaleón", hint: "Adaptación" },
    { word: "Salamandra", hint: "Regeneración" },
    { word: "Rana", hint: "Metamorfosis" },
    { word: "Cocodrilo", hint: "Ancestral" },
    { word: "Iguana", hint: "Camuflaje" },
    { word: "Gecko", hint: "Adhesión" },
    { word: "Cobra", hint: "Hipnosis" },
    { word: "Pitón", hint: "Constricción" },
    { word: "Mamba", hint: "Rapidez" },
    { word: "Lagartija", hint: "Cola perdida" },
    { word: "Salamanquesa", hint: "Nocturna" },
    { word: "Tarántula", hint: "Peluda" },
    { word: "Viuda negra", hint: "Fatal" },
    { word: "Mantis religiosa", hint: "Oración" },
    { word: "Libélula", hint: "Acrobacia" },
    { word: "Ciempiés", hint: "Múltiple" },
    { word: "Milpiés", hint: "Enrollar" },
    { word: "Luciérnaga", hint: "Bioluminiscencia" },
    { word: "Grillo", hint: "Serenata" },
    { word: "Saltamontes", hint: "Salto" },
    { word: "Mariquita", hint: "Suerte" },
    { word: "Escarabajo", hint: "Armadura" },
    { word: "Mosca", hint: "Persistencia" },
    { word: "Mosquito", hint: "Irritación" },
    { word: "Avispa", hint: "Agresión" },
    { word: "Tábano", hint: "Molestia" },
    { word: "Polilla", hint: "Luz" },
    { word: "Gusano", hint: "Metamorfosis" },
    { word: "Lombriz", hint: "Tierra" },
    { word: "Sanguijuela", hint: "Succión" },
    { word: "Estrella de mar", hint: "Regeneración" },
    { word: "Erizo de mar", hint: "Defensa" },
    { word: "Pepino de mar", hint: "Viscosidad" },
    { word: "Anémona", hint: "Simbiosis" },
    { word: "Coral", hint: "Colonia" },
    { word: "Esponja", hint: "Filtración" },
    { word: "Nautilo", hint: "Espiral" },
    { word: "Calamar", hint: "Tinta" },
    { word: "Sepia", hint: "Camuflaje" },
    { word: "Ostra", hint: "Perla" },
    { word: "Mejillón", hint: "Adherencia" },
    { word: "Almeja", hint: "Concha" },
    { word: "Vieira", hint: "Abanico" },
    { word: "Caracola", hint: "Eco" },
    { word: "Langosta", hint: "Lujo" },
    { word: "Camarón", hint: "Curvatura" },
    { word: "Gamba", hint: "Delicadeza" },
    { word: "Cigala", hint: "Pinzas" },
    { word: "Centolla", hint: "Espinas" },
    { word: "Buey de mar", hint: "Robustez" },
    { word: "Nécora", hint: "Pequeñez" },
    { word: "Percebes", hint: "Rocas" },
    { word: "Bogavante", hint: "Tenazas" },
    { word: "Trucha", hint: "Río" },
    { word: "Salmón", hint: "Corriente" },
    { word: "Atún", hint: "Velocidad" },
    { word: "Pez espada", hint: "Duelo" },

    // Lugares (100)
    { word: "Árbol de Navidad", hint: "Aguja" },
    { word: "Hospital", hint: "Turno" },
    { word: "Biblioteca", hint: "Respeto" },
    { word: "Cine", hint: "Oscuridad" },
    { word: "Aeropuerto", hint: "Despedida" },
    { word: "Escuela", hint: "Eco" },
    { word: "Hotel", hint: "Temporal" },
    { word: "Playa", hint: "Horizonte" },
    { word: "Montaña", hint: "Pulmón" },
    { word: "Museo", hint: "Silencio" },
    { word: "Teatro", hint: "Telón" },
    { word: "Estadio", hint: "Euforia" },
    { word: "Parque", hint: "Respiro" },
    { word: "Zoo", hint: "Cautiverio" },
    { word: "Acuario", hint: "Azul" },
    { word: "Planetario", hint: "Infinito" },
    { word: "Catedral", hint: "Eco divino" },
    { word: "Templo", hint: "Devoción" },
    { word: "Mezquita", hint: "Orientación" },
    { word: "Sinagoga", hint: "Comunidad" },
    { word: "Castillo", hint: "Historia" },
    { word: "Fortaleza", hint: "Defensa" },
    { word: "Ruinas", hint: "Tiempo" },
    { word: "Pirámide", hint: "Eternidad" },
    { word: "Faro", hint: "Guía" },
    { word: "Puente", hint: "Conexión" },
    { word: "Túnel", hint: "Travesía" },
    { word: "Cueva", hint: "Refugio" },
    { word: "Bosque", hint: "Murmullo" },
    { word: "Selva", hint: "Humedad" },
    { word: "Desierto", hint: "Sed" },
    { word: "Oasis", hint: "Esperanza" },
    { word: "Volcán", hint: "Ira" },
    { word: "Glaciar", hint: "Inmóvil" },
    { word: "Cañón", hint: "Profundidad" },
    { word: "Valle", hint: "Refugio" },
    { word: "Pradera", hint: "Viento" },
    { word: "Pantano", hint: "Estancado" },
    { word: "Lago", hint: "Calma" },
    { word: "Río", hint: "Fluir" },
    { word: "Cascada", hint: "Caída" },
    { word: "Manantial", hint: "Origen" },
    { word: "Océano", hint: "Inmensidad" },
    { word: "Mar", hint: "Sal" },
    { word: "Bahía", hint: "Refugio" },
    { word: "Península", hint: "Extensión" },
    { word: "Isla", hint: "Aislamiento" },
    { word: "Archipiélago", hint: "Fragmentos" },
    { word: "Atolón", hint: "Anillo" },
    { word: "Arrecife", hint: "Barrera" },
    { word: "Acantilado", hint: "Vértigo" },
    { word: "Costa", hint: "Límite" },
    { word: "Litoral", hint: "Frontera" },
    { word: "Puerto", hint: "Llegada" },
    { word: "Muelle", hint: "Espera" },
    { word: "Embarcadero", hint: "Transición" },
    { word: "Malecón", hint: "Paseo" },
    { word: "Rompeolas", hint: "Protección" },
    { word: "Faro", hint: "Vigía" },
    { word: "Estación", hint: "Tránsito" },
    { word: "Terminal", hint: "Final" },
    { word: "Andén", hint: "Espera" },
    { word: "Vías", hint: "Dirección" },
    { word: "Autopista", hint: "Velocidad" },
    { word: "Carretera", hint: "Ruta" },
    { word: "Camino", hint: "Travesía" },
    { word: "Sendero", hint: "Exploración" },
    { word: "Callejón", hint: "Estrechez" },
    { word: "Bulevar", hint: "Elegancia" },
    { word: "Avenida", hint: "Amplitud" },
    { word: "Plaza", hint: "Encuentro" },
    { word: "Parque", hint: "Verde" },
    { word: "Jardín", hint: "Cultivo" },
    { word: "Huerto", hint: "Cosecha" },
    { word: "Viñedo", hint: "Uvas" },
    { word: "Campo", hint: "Libertad" },
    { word: "Granja", hint: "Trabajo" },
    { word: "Rancho", hint: "Ganado" },
    { word: "Establo", hint: "Refugio animal" },
    { word: "Corral", hint: "Cerco" },
    { word: "Gallinero", hint: "Huevos" },
    { word: "Colmena", hint: "Zumbido" },
    { word: "Nido", hint: "Hogar temporal" },
    { word: "Madriguera", hint: "Escondite" },
    { word: "Guarida", hint: "Protección" },
    { word: "Cementerio", hint: "Memoria" },
    { word: "Panteón", hint: "Descanso" },
    { word: "Mausoleo", hint: "Monumento" },
    { word: "Cripta", hint: "Subterráneo" },
    { word: "Catacumbas", hint: "Laberinto" },
    { word: "Tumba", hint: "Final" },
    { word: "Lápida", hint: "Recuerdo" },
    { word: "Monumento", hint: "Homenaje" },
    { word: "Estatua", hint: "Inmortalidad" },
    { word: "Obelisco", hint: "Altura" },
    { word: "Columna", hint: "Soporte" },
    { word: "Arco", hint: "Triunfo" },
    { word: "Cúpula", hint: "Cielo" },
    { word: "Torre", hint: "Elevación" },

    // Objetos (150)
    { word: "Reloj", hint: "Pulso" },
    { word: "Teléfono", hint: "Interrupción" },
    { word: "Espejo", hint: "Ensayo" },
    { word: "Libro", hint: "Portal" },
    { word: "Lápiz", hint: "Borrador" },
    { word: "Papel", hint: "Blanco" },
    { word: "Tinta", hint: "Permanencia" },
    { word: "Pluma", hint: "Elegancia" },
    { word: "Bolígrafo", hint: "Cotidiano" },
    { word: "Cuaderno", hint: "Memorias" },
    { word: "Agenda", hint: "Orden" },
    { word: "Calendario", hint: "Cuenta atrás" },
    { word: "Computadora", hint: "Ventanas" },
    { word: "Teclado", hint: "Clic" },
    { word: "Mouse", hint: "Cursor" },
    { word: "Pantalla", hint: "Luz azul" },
    { word: "Impresora", hint: "Papel atascado" },
    { word: "Escáner", hint: "Copia" },
    { word: "USB", hint: "Portátil" },
    { word: "Disco duro", hint: "Almacén" },
    { word: "Auriculares", hint: "Aislamiento" },
    { word: "Micrófono", hint: "Amplificación" },
    { word: "Altavoz", hint: "Resonancia" },
    { word: "Cámara", hint: "Captura" },
    { word: "Lente", hint: "Enfoque" },
    { word: "Trípode", hint: "Estabilidad" },
    { word: "Flash", hint: "Destello" },
    { word: "Proyector", hint: "Ampliación" },
    { word: "Radio", hint: "Ondas" },
    { word: "Televisión", hint: "Hipnosis" },
    { word: "Control remoto", hint: "Distancia" },
    { word: "Cable", hint: "Conexión" },
    { word: "Enchufe", hint: "Energía" },
    { word: "Interruptor", hint: "Cambio" },
    { word: "Bombilla", hint: "Idea" },
    { word: "Lámpara", hint: "Círculo de luz" },
    { word: "Linterna", hint: "Exploración" },
    { word: "Vela", hint: "Romántico" },
    { word: "Cerilla", hint: "Chispa" },
    { word: "Encendedor", hint: "Fuego" },
    { word: "Cigarrillo", hint: "Pausa" },
    { word: "Pipa", hint: "Reflexión" },
    { word: "Puro", hint: "Celebración" },
    { word: "Cenicero", hint: "Ceniza" },
    { word: "Botella", hint: "Mensaje" },
    { word: "Vaso", hint: "Transparencia" },
    { word: "Copa", hint: "Brindis" },
    { word: "Taza", hint: "Calor" },
    { word: "Jarra", hint: "Compartir" },
    { word: "Tetera", hint: "Ceremonia" },
    { word: "Cafetera", hint: "Despertar" },
    { word: "Licuadora", hint: "Mezcla" },
    { word: "Batidora", hint: "Espuma" },
    { word: "Horno", hint: "Transformación" },
    { word: "Microondas", hint: "Rapidez" },
    { word: "Estufa", hint: "Fuego controlado" },
    { word: "Refrigerador", hint: "Preservación" },
    { word: "Congelador", hint: "Suspensión" },
    { word: "Lavavajillas", hint: "Automatización" },
    { word: "Lavadora", hint: "Ciclo" },
    { word: "Secadora", hint: "Calor" },
    { word: "Plancha", hint: "Alisar" },
    { word: "Aspiradora", hint: "Succión" },
    { word: "Escoba", hint: "Barrido" },
    { word: "Trapeador", hint: "Humedad" },
    { word: "Cubo", hint: "Agua" },
    { word: "Esponja", hint: "Absorción" },
    { word: "Jabón", hint: "Espuma" },
    { word: "Detergente", hint: "Limpieza" },
    { word: "Toalla", hint: "Secado" },
    { word: "Sábana", hint: "Descanso" },
    { word: "Almohada", hint: "Sueños" },
    { word: "Colchón", hint: "Soporte" },
    { word: "Manta", hint: "Abrigo" },
    { word: "Edredón", hint: "Calidez" },
    { word: "Cojín", hint: "Comodidad" },
    { word: "Cortina", hint: "Privacidad" },
    { word: "Persiana", hint: "Control de luz" },
    { word: "Ventana", hint: "Vista" },
    { word: "Puerta", hint: "Umbral" },
    { word: "Cerradura", hint: "Seguridad" },
    { word: "Llave", hint: "Acceso" },
    { word: "Manija", hint: "Giro" },
    { word: "Bisagra", hint: "Movimiento" },
    { word: "Pomo", hint: "Apertura" },
    { word: "Picaporte", hint: "Cierre" },
    { word: "Timbre", hint: "Anuncio" },
    { word: "Aldaba", hint: "Golpe" },
    { word: "Buzón", hint: "Mensajes" },
    { word: "Escalera", hint: "Ascenso" },
    { word: "Peldaño", hint: "Paso" },
    { word: "Barandilla", hint: "Apoyo" },
    { word: "Pasamanos", hint: "Guía" },
    { word: "Ascensor", hint: "Suspensión" },
    { word: "Rampa", hint: "Inclinación" },
    { word: "Balcón", hint: "Exterior" },
    { word: "Terraza", hint: "Cielo abierto" },
    { word: "Jardín", hint: "Verde" },
    { word: "Patio", hint: "Centro" },
    { word: "Garaje", hint: "Refugio vehicular" },
    { word: "Sótano", hint: "Profundidad" },
    { word: "Ático", hint: "Altura" },
    { word: "Techo", hint: "Protección" },
    { word: "Pared", hint: "División" },
    { word: "Suelo", hint: "Base" },
    { word: "Ventilador", hint: "Brisa artificial" },
    { word: "Aire acondicionado", hint: "Clima controlado" },
    { word: "Calefacción", hint: "Calor artificial" },
    { word: "Radiador", hint: "Emisión" },
    { word: "Chimenea", hint: "Humo" },
    { word: "Estufa de leña", hint: "Crepitar" },
    { word: "Paraguas", hint: "Protección portátil" },
    { word: "Sombrilla", hint: "Sombra móvil" },
    { word: "Gorra", hint: "Visera" },
    { word: "Sombrero", hint: "Estilo" },
    { word: "Bufanda", hint: "Cuello abrigado" },
    { word: "Guantes", hint: "Dedos protegidos" },
    { word: "Calcetines", hint: "Pies cubiertos" },
    { word: "Zapatos", hint: "Pisada" },
    { word: "Botas", hint: "Aventura" },
    { word: "Zapatillas", hint: "Comodidad" },
    { word: "Sandalias", hint: "Libertad" },
    { word: "Chanclas", hint: "Playa" },
    { word: "Tacones", hint: "Altura artificial" },
    { word: "Cinturón", hint: "Ajuste" },
    { word: "Corbata", hint: "Formalidad" },
    { word: "Pajarita", hint: "Elegancia" },
    { word: "Tirantes", hint: "Suspensión" },
    { word: "Bolso", hint: "Portátil" },
    { word: "Mochila", hint: "Carga" },
    { word: "Maleta", hint: "Viaje" },
    { word: "Cartera", hint: "Identidad" },
    { word: "Billetera", hint: "Dinero" },
    { word: "Monedero", hint: "Cambio" },
    { word: "Reloj de pulsera", hint: "Tiempo personal" },
    { word: "Anillo", hint: "Círculo eterno" },
    { word: "Collar", hint: "Adorno" },
    { word: "Pulsera", hint: "Muñeca" },
    { word: "Pendientes", hint: "Lóbulo" },
    { word: "Broche", hint: "Sujeción decorativa" },

    // Comida y Bebida (100)
    { word: "Café", hint: "Ritual" },
    { word: "Pizza", hint: "Rebanada" },
    { word: "Pan", hint: "Básico" },
    { word: "Leche", hint: "Infancia" },
    { word: "Queso", hint: "Maduración" },
    { word: "Vino", hint: "Tiempo embotellado" },
    { word: "Cerveza", hint: "Espuma" },
    { word: "Agua", hint: "Vida" },
    { word: "Jugo", hint: "Fresco" },
    { word: "Refresco", hint: "Burbujas" },
    { word: "Té", hint: "Calma" },
    { word: "Chocolate", hint: "Tentación" },
    { word: "Helado", hint: "Frío dulce" },
    { word: "Pastel", hint: "Celebración" },
    { word: "Galleta", hint: "Miga" },
    { word: "Caramelo", hint: "Pegajoso" },
    { word: "Chicle", hint: "Masticar" },
    { word: "Miel", hint: "Dorado" },
    { word: "Azúcar", hint: "Dulzura" },
    { word: "Sal", hint: "Conservación" },
    { word: "Pimienta", hint: "Picante" },
    { word: "Canela", hint: "Aroma" },
    { word: "Vainilla", hint: "Suave" },
    { word: "Menta", hint: "Frescura" },
    { word: "Ajo", hint: "Aliento" },
    { word: "Cebolla", hint: "Lágrimas" },
    { word: "Tomate", hint: "Rojo jugoso" },
    { word: "Lechuga", hint: "Crujiente" },
    { word: "Zanahoria", hint: "Naranja" },
    { word: "Papa", hint: "Versátil" },
    { word: "Arroz", hint: "Grano" },
    { word: "Pasta", hint: "Italia" },
    { word: "Fideos", hint: "Sopa" },
    { word: "Sopa", hint: "Caliente líquido" },
    { word: "Ensalada", hint: "Verde" },
    { word: "Hamburguesa", hint: "Capas" },
    { word: "Hot dog", hint: "Salchicha" },
    { word: "Taco", hint: "Tortilla" },
    { word: "Burrito", hint: "Enrollado" },
    { word: "Sushi", hint: "Crudo" },
    { word: "Ramen", hint: "Caldo" },
    { word: "Tempura", hint: "Frito japonés" },
    { word: "Paella", hint: "Arroz español" },
    { word: "Tortilla", hint: "Huevo español" },
    { word: "Gazpacho", hint: "Frío" },
    { word: "Tapas", hint: "Pequeño" },
    { word: "Croissant", hint: "Hojaldrado" },
    { word: "Baguette", hint: "Francia" },
    { word: "Panini", hint: "Prensado" },
    { word: "Sandwich", hint: "Entre pan" },
    { word: "Wrap", hint: "Envuelto" },
    { word: "Bagel", hint: "Agujero" },
    { word: "Donut", hint: "Redondo dulce" },
    { word: "Muffin", hint: "Molde" },
    { word: "Cupcake", hint: "Individual" },
    { word: "Brownie", hint: "Chocolate denso" },
    { word: "Cookie", hint: "Chispas" },
    { word: "Waffle", hint: "Cuadros" },
    { word: "Panqueque", hint: "Apilado" },
    { word: "Crepa", hint: "Delgado" },
    { word: "Tostada", hint: "Dorado" },
    { word: "Mermelada", hint: "Frutal" },
    { word: "Mantequilla", hint: "Untable" },
    { word: "Mayonesa", hint: "Emulsión" },
    { word: "Ketchup", hint: "Rojo dulce" },
    { word: "Mostaza", hint: "Amarillo picante" },
    { word: "Salsa", hint: "Acompañamiento" },
    { word: "Vinagre", hint: "Ácido" },
    { word: "Aceite", hint: "Líquido graso" },
    { word: "Limón", hint: "Cítrico ácido" },
    { word: "Naranja", hint: "Vitamina" },
    { word: "Manzana", hint: "Prohibida" },
    { word: "Banana", hint: "Potasio" },
    { word: "Fresa", hint: "Rojo pequeño" },
    { word: "Uva", hint: "Racimo" },
    { word: "Sandía", hint: "Verano" },
    { word: "Melón", hint: "Dulce verde" },
    { word: "Piña", hint: "Corona" },
    { word: "Mango", hint: "Tropical" },
    { word: "Papaya", hint: "Naranja tropical" },
    { word: "Coco", hint: "Isla" },
    { word: "Kiwi", hint: "Peludo" },
    { word: "Durazno", hint: "Aterciopelado" },
    { word: "Ciruela", hint: "Morado" },
    { word: "Cereza", hint: "Hueso" },
    { word: "Pera", hint: "Forma" },
    { word: "Higo", hint: "Antiguo" },
    { word: "Dátil", hint: "Desierto" },
    { word: "Almendra", hint: "Nuez" },
    { word: "Nuez", hint: "Cáscara dura" },
    { word: "Avellana", hint: "Pequeña redonda" },
    { word: "Pistacho", hint: "Verde" },
    { word: "Cacahuate", hint: "Legumbre" },
    { word: "Castaña", hint: "Otoño" },

    // Fenómenos Naturales (50)
    { word: "Lluvia", hint: "Vidrio" },
    { word: "Nieve", hint: "Silencio blanco" },
    { word: "Granizo", hint: "Golpe helado" },
    { word: "Trueno", hint: "Rugido" },
    { word: "Rayo", hint: "Zigzag" },
    { word: "Relámpago", hint: "Destello" },
    { word: "Tormenta", hint: "Furia" },
    { word: "Huracán", hint: "Espiral" },
    { word: "Tornado", hint: "Embudo" },
    { word: "Terremoto", hint: "Temblor" },
    { word: "Tsunami", hint: "Ola gigante" },
    { word: "Avalancha", hint: "Cascada blanca" },
    { word: "Erupción", hint: "Explosión" },
    { word: "Eclipse", hint: "Sombra cósmica" },
    { word: "Aurora", hint: "Danza celeste" },
    { word: "Arcoíris", hint: "Puente de colores" },
    { word: "Niebla", hint: "Visibilidad" },
    { word: "Neblina", hint: "Misterio" },
    { word: "Rocío", hint: "Perlas matutinas" },
    { word: "Escarcha", hint: "Cristales" },
    { word: "Helada", hint: "Congelación" },
    { word: "Sequía", hint: "Sed" },
    { word: "Inundación", hint: "Desborde" },
    { word: "Maremoto", hint: "Ola sísmica" },
    { word: "Deslizamiento", hint: "Tierra móvil" },
    { word: "Alud", hint: "Avalancha" },
    { word: "Ventisca", hint: "Nieve ventosa" },
    { word: "Ciclón", hint: "Giro atmosférico" },
    { word: "Monzón", hint: "Estación lluviosa" },
    { word: "Brisa", hint: "Viento suave" },
    { word: "Vendaval", hint: "Viento fuerte" },
    { word: "Ráfaga", hint: "Golpe de aire" },
    { word: "Tifón", hint: "Huracán asiático" },
    { word: "Marejada", hint: "Mar agitado" },
    { word: "Oleaje", hint: "Ondas marinas" },
    { word: "Corriente", hint: "Flujo" },
    { word: "Marea", hint: "Subida y bajada" },
    { word: "Resaca", hint: "Retroceso" },
    { word: "Remolino", hint: "Vórtice" },
    { word: "Torbellino", hint: "Giro rápido" },
    { word: "Tempestad", hint: "Furia marina" },
    { word: "Calma", hint: "Quietud" },
    { word: "Sequía", hint: "Ausencia" },
    { word: "Diluvio", hint: "Bíblico" },
    { word: "Llovizna", hint: "Gotas pequeñas" },
    { word: "Aguacero", hint: "Lluvia intensa" },
    { word: "Chaparrón", hint: "Lluvia breve" },
    { word: "Chubasco", hint: "Lluvia repentina" },
    { word: "Tromba", hint: "Columna de agua" },
    { word: "Manga", hint: "Tornado marino" },

    // Emociones y Conceptos (100)
    { word: "Amor", hint: "Corazón" },
    { word: "Odio", hint: "Veneno" },
    { word: "Alegría", hint: "Risa" },
    { word: "Tristeza", hint: "Lágrima" },
    { word: "Miedo", hint: "Parálisis" },
    { word: "Valentía", hint: "Acción" },
    { word: "Paz", hint: "Silencio interior" },
    { word: "Guerra", hint: "Conflicto" },
    { word: "Libertad", hint: "Vuelo" },
    { word: "Esclavitud", hint: "Cadenas" },
    { word: "Verdad", hint: "Luz" },
    { word: "Mentira", hint: "Máscara" },
    { word: "Justicia", hint: "Balanza" },
    { word: "Injusticia", hint: "Desequilibrio" },
    { word: "Esperanza", hint: "Mañana" },
    { word: "Desesperación", hint: "Abismo" },
    { word: "Fe", hint: "Invisible" },
    { word: "Duda", hint: "Vacilación" },
    { word: "Conocimiento", hint: "Poder" },
    { word: "Ignorancia", hint: "Oscuridad" },
    { word: "Sabiduría", hint: "Experiencia" },
    { word: "Locura", hint: "Genio" },
    { word: "Cordura", hint: "Normalidad" },
    { word: "Belleza", hint: "Subjetivo" },
    { word: "Fealdad", hint: "Rechazo" },
    { word: "Bondad", hint: "Altruismo" },
    { word: "Maldad", hint: "Egoísmo" },
    { word: "Generosidad", hint: "Dar" },
    { word: "Avaricia", hint: "Acumular" },
    { word: "Envidia", hint: "Verde" },
    { word: "Gratitud", hint: "Gracias" },
    { word: "Orgullo", hint: "León" },
    { word: "Humildad", hint: "Tierra" },
    { word: "Ira", hint: "Rojo" },
    { word: "Calma", hint: "Azul" },
    { word: "Paciencia", hint: "Espera" },
    { word: "Impaciencia", hint: "Urgencia" },
    { word: "Tolerancia", hint: "Aceptación" },
    { word: "Intolerancia", hint: "Rechazo" },
    { word: "Respeto", hint: "Reverencia" },
    { word: "Desprecio", hint: "Desdén" },
    { word: "Admiración", hint: "Asombro" },
    { word: "Compasión", hint: "Empatía" },
    { word: "Crueldad", hint: "Sadismo" },
    { word: "Perdón", hint: "Liberación" },
    { word: "Rencor", hint: "Peso" },
    { word: "Venganza", hint: "Ajuste de cuentas" },
    { word: "Misericordia", hint: "Piedad" },
    { word: "Lealtad", hint: "Fidelidad" },
    { word: "Traición", hint: "Puñal" },
    { word: "Confianza", hint: "Puente" },
    { word: "Desconfianza", hint: "Muro" },
    { word: "Honestidad", hint: "Transparencia" },
    { word: "Deshonestidad", hint: "Opacidad" },
    { word: "Sinceridad", hint: "Franqueza" },
    { word: "Hipocresía", hint: "Doble cara" },
    { word: "Valentía", hint: "Coraje" },
    { word: "Cobardía", hint: "Huida" },
    { word: "Determinación", hint: "Voluntad" },
    { word: "Indecisión", hint: "Duda" },
    { word: "Disciplina", hint: "Orden" },
    { word: "Caos", hint: "Desorden" },
    { word: "Éxito", hint: "Cima" },
    { word: "Fracaso", hint: "Aprendizaje" },
    { word: "Victoria", hint: "Triunfo" },
    { word: "Derrota", hint: "Caída" },
    { word: "Fuerza", hint: "Poder" },
    { word: "Debilidad", hint: "Vulnerabilidad" },
    { word: "Salud", hint: "Vitalidad" },
    { word: "Enfermedad", hint: "Debilitación" },
    { word: "Vida", hint: "Latido" },
    { word: "Muerte", hint: "Final" },
    { word: "Nacimiento", hint: "Inicio" },
    { word: "Crecimiento", hint: "Desarrollo" },
    { word: "Madurez", hint: "Sabiduría" },
    { word: "Vejez", hint: "Experiencia" },
    { word: "Juventud", hint: "Energía" },
    { word: "Infancia", hint: "Inocencia" },
    { word: "Adolescencia", hint: "Transición" },
    { word: "Adultez", hint: "Responsabilidad" },
    { word: "Tiempo", hint: "Reloj de arena" },
    { word: "Eternidad", hint: "Infinito" },
    { word: "Momento", hint: "Instante" },
    { word: "Pasado", hint: "Memoria" },
    { word: "Presente", hint: "Ahora" },
    { word: "Futuro", hint: "Incertidumbre" },
    { word: "Destino", hint: "Predestinación" },
    { word: "Azar", hint: "Caos" },
    { word: "Suerte", hint: "Fortuna" },
    { word: "Desgracia", hint: "Infortunio" },
    { word: "Fortuna", hint: "Riqueza" },
    { word: "Pobreza", hint: "Carencia" },
    { word: "Abundancia", hint: "Plenitud" },
    { word: "Escasez", hint: "Falta" },
    { word: "Equilibrio", hint: "Balance" },
    { word: "Desequilibrio", hint: "Inclinación" },

    // Profesiones (50)
    { word: "Médico", hint: "Bata blanca" },
    { word: "Enfermera", hint: "Cuidado" },
    { word: "Doctor", hint: "Diagnóstico" },
    { word: "Dentista", hint: "Dientes" },
    { word: "Psicólogo", hint: "Mente" },
    { word: "Psiquiatra", hint: "Medicación" },
    { word: "Terapeuta", hint: "Sanación" },
    { word: "Cirujano", hint: "Bisturí" },
    { word: "Veterinario", hint: "Animales" },
    { word: "Farmacéutico", hint: "Recetas" },
    { word: "Maestro", hint: "Pizarra" },
    { word: "Profesor", hint: "Lección" },
    { word: "Instructor", hint: "Entrenamiento" },
    { word: "Tutor", hint: "Personalizado" },
    { word: "Director", hint: "Autoridad" },
    { word: "Rector", hint: "Universidad" },
    { word: "Abogado", hint: "Ley" },
    { word: "Juez", hint: "Martillo" },
    { word: "Fiscal", hint: "Acusación" },
    { word: "Notario", hint: "Firma" },
    { word: "Policía", hint: "Orden" },
    { word: "Detective", hint: "Investigación" },
    { word: "Bombero", hint: "Fuego" },
    { word: "Soldado", hint: "Disciplina" },
    { word: "Militar", hint: "Jerarquía" },
    { word: "Piloto", hint: "Altitud" },
    { word: "Azafata", hint: "Servicio" },
    { word: "Capitán", hint: "Timón" },
    { word: "Marinero", hint: "Mar" },
    { word: "Pescador", hint: "Red" },
    { word: "Agricultor", hint: "Cosecha" },
    { word: "Ganadero", hint: "Rebaño" },
    { word: "Ingeniero", hint: "Cálculo" },
    { word: "Arquitecto", hint: "Planos" },
    { word: "Albañil", hint: "Cemento" },
    { word: "Carpintero", hint: "Madera" },
    { word: "Plomero", hint: "Tubería" },
    { word: "Electricista", hint: "Cables" },
    { word: "Mecánico", hint: "Herramientas" },
    { word: "Chef", hint: "Cocina" },
    { word: "Cocinero", hint: "Sartén" },
    { word: "Mesero", hint: "Propina" },
    { word: "Barista", hint: "Espresso" },
    { word: "Panadero", hint: "Horno" },
    { word: "Pastelero", hint: "Dulce" },
    { word: "Carnicero", hint: "Cuchillo" },
    { word: "Pescadero", hint: "Escamas" },
    { word: "Verdulero", hint: "Frescura" },
    { word: "Tendero", hint: "Mostrador" },
    { word: "Vendedor", hint: "Persuasión" },

    // Deportes y Actividades (50)
    { word: "Fútbol", hint: "Once" },
    { word: "Baloncesto", hint: "Aro" },
    { word: "Tenis", hint: "Red" },
    { word: "Voleibol", hint: "Bloqueo" },
    { word: "Natación", hint: "Clorado" },
    { word: "Ciclismo", hint: "Cadena" },
    { word: "Atletismo", hint: "Pista" },
    { word: "Gimnasia", hint: "Flexibilidad" },
    { word: "Boxeo", hint: "Puño" },
    { word: "Karate", hint: "Cinturón" },
    { word: "Judo", hint: "Tatami" },
    { word: "Taekwondo", hint: "Patada" },
    { word: "Esgrima", hint: "Espada" },
    { word: "Arquería", hint: "Diana" },
    { word: "Golf", hint: "Hoyo" },
    { word: "Béisbol", hint: "Bate" },
    { word: "Softbol", hint: "Guante" },
    { word: "Rugby", hint: "Ovalado" },
    { word: "Hockey", hint: "Palo" },
    { word: "Polo", hint: "Caballo" },
    { word: "Esquí", hint: "Nieve" },
    { word: "Snowboard", hint: "Tabla" },
    { word: "Surf", hint: "Ola" },
    { word: "Buceo", hint: "Profundidad" },
    { word: "Vela", hint: "Viento" },
    { word: "Remo", hint: "Sincronización" },
    { word: "Piragüismo", hint: "Corriente" },
    { word: "Rafting", hint: "Adrenalina" },
    { word: "Escalada", hint: "Agarre" },
    { word: "Alpinismo", hint: "Cumbre" },
    { word: "Paracaidismo", hint: "Caída libre" },
    { word: "Ala delta", hint: "Planeo" },
    { word: "Parapente", hint: "Vuelo" },
    { word: "Bungee", hint: "Elástico" },
    { word: "Parkour", hint: "Urbano" },
    { word: "Yoga", hint: "Equilibrio" },
    { word: "Pilates", hint: "Core" },
    { word: "Zumba", hint: "Ritmo" },
    { word: "Aeróbicos", hint: "Cardio" },
    { word: "Crossfit", hint: "Intensidad" },
    { word: "Halterofilia", hint: "Peso" },
    { word: "Maratón", hint: "Resistencia" },
    { word: "Triatlón", hint: "Triple" },
    { word: "Pentatlón", hint: "Cinco" },
    { word: "Decatlón", hint: "Diez" },
    { word: "Ciclismo de montaña", hint: "Terreno" },
    { word: "BMX", hint: "Acrobacia" },
    { word: "Skateboard", hint: "Tabla con ruedas" },
    { word: "Patinaje", hint: "Deslizar" },
    { word: "Roller", hint: "Línea" },

    // Tecnología y Ciencia (50)
    { word: "Internet", hint: "Conexión global" },
    { word: "Wi-Fi", hint: "Inalámbrico" },
    { word: "Bluetooth", hint: "Diente azul" },
    { word: "GPS", hint: "Ubicación" },
    { word: "Satélite", hint: "Órbita" },
    { word: "Cohete", hint: "Propulsión" },
    { word: "Nave espacial", hint: "Cosmos" },
    { word: "Telescopio", hint: "Lejos" },
    { word: "Microscopio", hint: "Pequeño" },
    { word: "ADN", hint: "Código genético" },
    { word: "Átomo", hint: "Indivisible" },
    { word: "Molécula", hint: "Unión" },
    { word: "Célula", hint: "Vida básica" },
    { word: "Bacteria", hint: "Microscópico" },
    { word: "Virus", hint: "Invasor" },
    { word: "Vacuna", hint: "Prevención" },
    { word: "Antibiótico", hint: "Combate" },
    { word: "Radiografía", hint: "Ver dentro" },
    { word: "Ultrasonido", hint: "Ondas" },
    { word: "Resonancia", hint: "Magnética" },
    { word: "Tomografía", hint: "Cortes" },
    { word: "Láser", hint: "Haz concentrado" },
    { word: "Holografía", hint: "Tres dimensiones" },
    { word: "Realidad virtual", hint: "Inmersión" },
    { word: "Realidad aumentada", hint: "Superposición" },
    { word: "Inteligencia artificial", hint: "Máquina pensante" },
    { word: "Robot", hint: "Automatizado" },
    { word: "Dron", hint: "Vuelo remoto" },
    { word: "Impresora 3D", hint: "Capa por capa" },
    { word: "Nanotecnología", hint: "Diminuto" },
    { word: "Biotecnología", hint: "Vida modificada" },
    { word: "Energía solar", hint: "Sol" },
    { word: "Energía eólica", hint: "Viento" },
    { word: "Energía nuclear", hint: "Átomo" },
    { word: "Batería", hint: "Almacenamiento" },
    { word: "Panel solar", hint: "Fotovoltaico" },
    { word: "Turbina", hint: "Giro" },
    { word: "Generador", hint: "Producción" },
    { word: "Motor", hint: "Movimiento" },
    { word: "Pistón", hint: "Vaivén" },
    { word: "Engranaje", hint: "Dientes" },
    { word: "Palanca", hint: "Fuerza" },
    { word: "Polea", hint: "Elevación" },
    { word: "Tornillo", hint: "Rosca" },
    { word: "Tuerca", hint: "Ajuste" },
    { word: "Perno", hint: "Unión" },
    { word: "Clavo", hint: "Penetración" },
    { word: "Martillo", hint: "Golpe" },
    { word: "Destornillador", hint: "Giro" },
    { word: "Llave inglesa", hint: "Ajustable" },

    // Música e Instrumentos (50)
    { word: "Piano", hint: "Teclas" },
    { word: "Guitarra", hint: "Seis cuerdas" },
    { word: "Violín", hint: "Arco" },
    { word: "Violonchelo", hint: "Grande y profundo" },
    { word: "Contrabajo", hint: "Grave" },
    { word: "Viola", hint: "Media" },
    { word: "Arpa", hint: "Ángel" },
    { word: "Flauta", hint: "Soplo" },
    { word: "Clarinete", hint: "Lengüeta" },
    { word: "Saxofón", hint: "Jazz" },
    { word: "Trompeta", hint: "Fanfarria" },
    { word: "Trombón", hint: "Vara" },
    { word: "Tuba", hint: "Grave grande" },
    { word: "Corneta", hint: "Militar" },
    { word: "Trompa", hint: "Circular" },
    { word: "Oboe", hint: "Doble lengüeta" },
    { word: "Fagot", hint: "Bajo de madera" },
    { word: "Armónica", hint: "Bolsillo" },
    { word: "Acordeón", hint: "Fuelle" },
    { word: "Banjo", hint: "Circular" },
    { word: "Mandolina", hint: "Pequeña" },
    { word: "Ukelele", hint: "Hawái" },
    { word: "Laúd", hint: "Medieval" },
    { word: "Cítara", hint: "Horizontal" },
    { word: "Balalaica", hint: "Triangular" },
    { word: "Sitar", hint: "India" },
    { word: "Tambor", hint: "Piel" },
    { word: "Batería", hint: "Kit" },
    { word: "Bombo", hint: "Gran golpe" },
    { word: "Platillos", hint: "Crash" },
    { word: "Bongó", hint: "Par" },
    { word: "Congas", hint: "Cuba" },
    { word: "Timbales", hint: "Metal" },
    { word: "Djembe", hint: "África" },
    { word: "Maracas", hint: "Sacudir" },
    { word: "Castañuelas", hint: "España" },
    { word: "Pandereta", hint: "Sonajas" },
    { word: "Triángulo", hint: "Ding" },
    { word: "Campana", hint: "Repique" },
    { word: "Gong", hint: "Resonancia" },
    { word: "Xilófono", hint: "Madera" },
    { word: "Marimba", hint: "Grande" },
    { word: "Vibráfono", hint: "Motorizado" },
    { word: "Metalófono", hint: "Metal" },
    { word: "Órgano", hint: "Tubos" },
    { word: "Sintetizador", hint: "Electrónico" },
    { word: "Theremin", hint: "Sin tocar" },
    { word: "Sampler", hint: "Grabación" },
    { word: "Metrónomo", hint: "Tiempo" },
    { word: "Afinador", hint: "Tono" },

    // Vehículos (50)
    { word: "Avión", hint: "Silencio" },
    { word: "Auto", hint: "Cuatro ruedas" },
    { word: "Moto", hint: "Dos ruedas" },
    { word: "Bicicleta", hint: "Pedales" },
    { word: "Camión", hint: "Carga" },
    { word: "Autobús", hint: "Pasajeros" },
    { word: "Tren", hint: "Rieles" },
    { word: "Metro", hint: "Subterráneo" },
    { word: "Tranvía", hint: "Cables" },
    { word: "Barco", hint: "Flotación" },
    { word: "Yate", hint: "Lujo marino" },
    { word: "Lancha", hint: "Rápida" },
    { word: "Submarino", hint: "Profundidad" },
    { word: "Helicóptero", hint: "Hélice" },
    { word: "Globo aerostático", hint: "Calor" },
    { word: "Cohete", hint: "Espacio" },
    { word: "Nave espacial", hint: "Estrellas" },
    { word: "Jet", hint: "Velocidad" },
    { word: "Planeador", hint: "Sin motor" },
    { word: "Parapente", hint: "Tela" },
    { word: "Ultraligero", hint: "Ligero" },
    { word: "Hidroavión", hint: "Agua" },
    { word: "Ambulancia", hint: "Emergencia" },
    { word: "Patrulla", hint: "Policía" },
    { word: "Camión de bomberos", hint: "Escalera" },
    { word: "Grúa", hint: "Elevación" },
    { word: "Excavadora", hint: "Tierra" },
    { word: "Bulldozer", hint: "Empuje" },
    { word: "Tractor", hint: "Campo" },
    { word: "Cosechadora", hint: "Recolección" },
    { word: "Montacargas", hint: "Carga vertical" },
    { word: "Carretilla", hint: "Manual" },
    { word: "Patineta", hint: "Skate" },
    { word: "Monopatín", hint: "Eléctrico" },
    { word: "Segway", hint: "Auto equilibrio" },
    { word: "Hoverboard", hint: "Futuro" },
    { word: "Triciclo", hint: "Tres" },
    { word: "Cuatriciclo", hint: "Todo terreno" },
    { word: "Scooter", hint: "Eléctrico pequeño" },
    { word: "Vespa", hint: "Italiana" },
    { word: "Chopper", hint: "Customizada" },
    { word: "Crucero", hint: "Viaje" },
    { word: "Ferry", hint: "Cruce" },
    { word: "Kayak", hint: "Remo doble" },
    { word: "Canoa", hint: "Remo simple" },
    { word: "Balsa", hint: "Flotador" },
    { word: "Velero", hint: "Vela" },
    { word: "Catamarán", hint: "Doble casco" },
    { word: "Jet ski", hint: "Agua rápida" },
    { word: "Tabla de surf", hint: "Ola" }
];

function getRandomWord() {
    const randomIndex = Math.floor(Math.random() * wordsDatabase.length);
    return wordsDatabase[randomIndex];
}

function generateRoomCode() {
    const characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
    let code = '';
    for (let i = 0; i < 6; i++) {
        code += characters.charAt(Math.floor(Math.random() * characters.length));
    }
    return code;
}

function selectImpostors(players, impostorCount) {
    const shuffled = [...players].sort(() => Math.random() - 0.5);
    const impostorIds = shuffled.slice(0, impostorCount).map(p => p.id);
    return impostorIds;
}

module.exports = {
    getRandomWord,
    generateRoomCode,
    selectImpostors
};