const wordsDatabase = [
    // Fiesta (200) - Ajustes
    { word: "Globo", hint: "Helio" },
    { word: "Confeti", hint: "Fragmentos" },
    { word: "Música", hint: "Decibeles" },
    { word: "Baile", hint: "Ritmo" },
    { word: "Torta", hint: "Capas" },
    { word: "Velas", hint: "Soplo" },
    { word: "Regalo", hint: "Envoltura" },
    { word: "Invitación", hint: "Confirmación" },
    { word: "Brindis", hint: "Cristal" },
    { word: "Champán", hint: "Corcho" },
    { word: "Cerveza", hint: "Malta" },
    { word: "Ron", hint: "Caribe" },
    { word: "Vodka", hint: "Destilado" },
    { word: "Tequila", hint: "Gusano" },
    { word: "Whisky", hint: "Bourbon" },
    { word: "Mojito", hint: "Hierbabuena" },
    { word: "Piña colada", hint: "Coco" },
    { word: "Margarita", hint: "Limón" },
    { word: "Karaoke", hint: "Letras" },
    { word: "DJ", hint: "Mezcla" },
    { word: "Bocaditos", hint: "Bandeja" },
    { word: "Pizza", hint: "Mozzarella" },
    { word: "Empanadas", hint: "Relleno" },
    { word: "Nachos", hint: "Cheddar" },
    { word: "Salsa", hint: "Cilantro" },
    { word: "Guacamole", hint: "Palta" },
    { word: "Papas fritas", hint: "Aceite" },
    { word: "Helado", hint: "Cremoso" },
    { word: "Gelatina", hint: "Temblor" },
    { word: "Ponche", hint: "Tazón" },
    { word: "Gaseosa", hint: "Burbujas" },
    { word: "Hielo", hint: "Cubos" },
    { word: "Vasos", hint: "Desechable" },
    { word: "Platos", hint: "Porcelana" },
    { word: "Servilletas", hint: "Doblado" },
    { word: "Mantel", hint: "Tela" },
    { word: "Sillas", hint: "Apilables" },
    { word: "Mesa", hint: "Superficie" },
    { word: "Luces", hint: "Intermitente" },
    { word: "Guirnalda", hint: "Colgante" },
    { word: "Serpentina", hint: "Espiral" },
    { word: "Máscara", hint: "Ocultar" },
    { word: "Disfraz", hint: "Personaje" },
    { word: "Sombrero", hint: "Copa" },
    { word: "Silbato", hint: "Árbitro" },
    { word: "Trompeta", hint: "Válvulas" },
    { word: "Batería", hint: "Platillos" },
    { word: "Guitarra", hint: "Trastes" },
    { word: "Micrófono", hint: "Amplificación" },
    { word: "Parlante", hint: "Woofer" },
    { word: "Foto", hint: "Instantánea" },
    { word: "Selfie", hint: "Brazo" },
    { word: "Video", hint: "Grabación" },
    { word: "Pista", hint: "Baile" },
    { word: "Anfitrión", hint: "Organizador" },
    { word: "Invitado", hint: "Lista" },
    { word: "Abrazo", hint: "Brazos" },
    { word: "Beso", hint: "Labios" },
    { word: "Risa", hint: "Carcajada" },
    { word: "Grito", hint: "Volumen" },
    { word: "Aplauso", hint: "Palmas" },
    { word: "Sorpresa", hint: "Ojos" },
    { word: "Animación", hint: "Energía" },
    { word: "Payaso", hint: "Nariz" },
    { word: "Mago", hint: "Sombrero" },
    { word: "Piñata", hint: "Palo" },
    { word: "Caramelos", hint: "Envoltura" },
    { word: "Chocolate", hint: "Cacao" },
    { word: "Chupetín", hint: "Palo" },
    { word: "Chicle", hint: "Masticar" },
    { word: "Palomitas", hint: "Explosión" },
    { word: "Algodón de azúcar", hint: "Nube" },
    { word: "Cumpleaños", hint: "Edad" },
    { word: "Aniversario", hint: "Fecha" },
    { word: "Graduación", hint: "Birrete" },
    { word: "Boda", hint: "Anillos" },
    { word: "Quinceañera", hint: "Vals" },
    { word: "Bautizo", hint: "Padrinos" },
    { word: "Despedida", hint: "Soltera" },
    { word: "Bienvenida", hint: "Llegada" },
    { word: "Inauguración", hint: "Cinta" },
    { word: "Lanzamiento", hint: "Debut" },
    { word: "Festival", hint: "Escenario" },
    { word: "Carnaval", hint: "Comparsas" },
    { word: "Feria", hint: "Stands" },
    { word: "Serenata", hint: "Ventana" },
    { word: "Pijamada", hint: "Almohadas" },
    { word: "Fogata", hint: "Leña" },
    { word: "Parrillada", hint: "Parrilla" },
    { word: "Picnic", hint: "Canasta" },
    { word: "Discoteca", hint: "Bola" },
    { word: "Bar", hint: "Barra" },
    { word: "Club", hint: "Membresía" },
    { word: "Terraza", hint: "Vista" },
    { word: "Jardín", hint: "Césped" },
    { word: "Salón", hint: "Eventos" },
    { word: "Playa", hint: "Arena" },
    { word: "Decoración", hint: "Adornos" },
    { word: "Tema", hint: "Concepto" },
    { word: "Elegante", hint: "Formal" },
    { word: "Casual", hint: "Relajado" },
    { word: "Tropical", hint: "Palmeras" },
    { word: "Retro", hint: "Vintage" },
    { word: "Neón", hint: "Fosforescente" },
    { word: "Brillos", hint: "Reflejo" },
    { word: "Plumas", hint: "Boa" },
    { word: "Flores", hint: "Pétalos" },
    { word: "Rosas", hint: "Espinas" },
    { word: "Orquídeas", hint: "Exóticas" },
    { word: "Girasoles", hint: "Amarillo" },
    { word: "Tulipanes", hint: "Holanda" },
    { word: "Margaritas", hint: "Blancas" },
    { word: "Lirios", hint: "Aroma" },
    { word: "Claveles", hint: "Rojos" },
    { word: "Jazmín", hint: "Perfume" },
    { word: "Lavanda", hint: "Púrpura" },
    { word: "Banderines", hint: "Triángulos" },
    { word: "Pompones", hint: "Papel" },
    { word: "Antorchas", hint: "Llama" },
    { word: "Pecera", hint: "Vidrio" },
    { word: "Fuente", hint: "Agua" },
    { word: "Burbujas", hint: "Jabón" },
    { word: "Humo", hint: "Niebla" },
    { word: "Espuma", hint: "Fiesta" },
    { word: "Cabina DJ", hint: "Mezclas" },
    { word: "Alfombra", hint: "Roja" },
    { word: "Cortina", hint: "Telón" },
    { word: "Proyector", hint: "Pantalla" },
    { word: "Pantalla", hint: "Visualización" },
    { word: "Hora loca", hint: "Máscaras" },
    { word: "Animador", hint: "Show" },
    { word: "Bartender", hint: "Coctelería" },
    { word: "Mesero", hint: "Bandeja" },
    { word: "Seguridad", hint: "Entrada" },
    { word: "Fotógrafo", hint: "Flash" },
    { word: "Camarógrafo", hint: "Trípode" },
    { word: "Playlist", hint: "Canciones" },
    { word: "Volumen", hint: "Amplificador" },
    { word: "Melodía", hint: "Tonada" },
    { word: "Coro", hint: "Estribillo" },
    { word: "Letra", hint: "Canción" },
    { word: "Remix", hint: "Versión" },
    { word: "Reggaeton", hint: "Perreo" },
    { word: "Salsa", hint: "Clave" },
    { word: "Merengue", hint: "Cadera" },
    { word: "Bachata", hint: "Romántico" },
    { word: "Cumbia", hint: "Colombiana" },
    { word: "Rock", hint: "Guitarra" },
    { word: "Pop", hint: "Pegajoso" },
    { word: "Electrónica", hint: "Sintetizador" },
    { word: "Hip hop", hint: "Freestyle" },
    { word: "Rap", hint: "Rimas" },
    { word: "Mariachi", hint: "Trompeta" },
    { word: "Samba", hint: "Brasil" },
    { word: "Champagne", hint: "Burbujas" },
    { word: "Brindis", hint: "Copa" },
    { word: "Fiesta", hint: "Celebración" },
    { word: "Diversión", hint: "Entretenimiento" },
    { word: "Ambiente", hint: "Atmósfera" },
    { word: "Energía", hint: "Vitalidad" },
    { word: "Ritmo", hint: "Compás" },
    { word: "Baile", hint: "Movimiento" },
    { word: "Música", hint: "Sonido" },
    { word: "Alegría", hint: "Felicidad" },
    { word: "Celebración", hint: "Festejo" },
    { word: "Recuerdo", hint: "Memoria" },
    { word: "Momento", hint: "Instante" },
    { word: "Experiencia", hint: "Vivencia" },
    { word: "Convivencia", hint: "Compartir" },
    { word: "Amistad", hint: "Amigos" },
    { word: "Familia", hint: "Parientes" },
    { word: "Compañía", hint: "Presencia" },
    { word: "Reunión", hint: "Encuentro" },
    { word: "Evento", hint: "Ocasión" },
    { word: "Ocasión", hint: "Momento" },
    { word: "Especial", hint: "Único" },
    { word: "Memorable", hint: "Inolvidable" },
    { word: "Divertido", hint: "Entretenido" },
    { word: "Emocionante", hint: "Excitante" },
    { word: "Increíble", hint: "Asombroso" },
    { word: "Espectacular", hint: "Impresionante" },
    { word: "Fantástico", hint: "Genial" },
    { word: "Maravilloso", hint: "Hermoso" },
    { word: "Perfecto", hint: "Ideal" },
    { word: "Genial", hint: "Excelente" },

    // Celebridades (conservar las conocidas globalmente)
    { word: "Shakira", hint: "Cadera" },
    { word: "Messi", hint: "Pulga" },
    { word: "Cristiano", hint: "Siete" },
    { word: "Neymar", hint: "Brasil" },
    { word: "Bad Bunny", hint: "Conejo" },
    { word: "Karol G", hint: "Bichota" },
    { word: "Maluma", hint: "Pretty" },
    { word: "J Balvin", hint: "Colores" },
    { word: "Daddy Yankee", hint: "Gasolina" },
    { word: "Ozuna", hint: "Negrito" },
    { word: "Anuel", hint: "Real" },
    { word: "Peso Pluma", hint: "Plumas" },
    { word: "Bizarrap", hint: "Sessions" },
    { word: "Natti Natasha", hint: "Criminal" },
    { word: "Becky G", hint: "Mayores" },
    { word: "Rosalía", hint: "Motomami" },
    { word: "Tini", hint: "Argentina" },
    { word: "Nicky Jam", hint: "Travesuras" },
    { word: "Romeo Santos", hint: "Bachata" },
    { word: "Marc Anthony", hint: "Salsa" },
    { word: "Enrique Iglesias", hint: "Bailando" },
    { word: "Luis Fonsi", hint: "Despacito" },
    { word: "Carlos Vives", hint: "Vallenato" },
    { word: "Maná", hint: "Mariposa" },
    { word: "Chayanne", hint: "Tiempo" },
    { word: "Farruko", hint: "Pepas" },
    { word: "Don Omar", hint: "Danza" },
    { word: "Camila Cabello", hint: "Havana" },
    { word: "Selena Gomez", hint: "Rare" },
    { word: "Ariana Grande", hint: "Thank" },
    { word: "Taylor Swift", hint: "Folklore" },
    { word: "Billie Eilish", hint: "Bad" },
    { word: "Dua Lipa", hint: "Levitating" },
    { word: "The Weeknd", hint: "Blinding" },
    { word: "Justin Bieber", hint: "Baby" },
    { word: "Beyoncé", hint: "Queen" },
    { word: "Rihanna", hint: "Umbrella" },
    { word: "Lady Gaga", hint: "Poker" },
    { word: "Katy Perry", hint: "Roar" },
    { word: "Madonna", hint: "Material" },
    { word: "Jennifer Lopez", hint: "Block" },
    { word: "Miley Cyrus", hint: "Wrecking" },
    { word: "Michael Jackson", hint: "King" },
    { word: "Nicki Minaj", hint: "Barbie" },
    { word: "Harry Styles", hint: "Watermelon" },
    { word: "BTS", hint: "Dynamite" },
    { word: "Tom Cruise", hint: "Mission" },
    { word: "Brad Pitt", hint: "Fight" },
    { word: "Leonardo DiCaprio", hint: "Titanic" },
    { word: "Johnny Depp", hint: "Pirates" },
    { word: "Will Smith", hint: "Fresh" },
    { word: "Dwayne Johnson", hint: "Rock" },
    { word: "Robert Downey", hint: "Iron" },
    { word: "Chris Evans", hint: "Captain" },
    { word: "Scarlett Johansson", hint: "Black" },
    { word: "Jennifer Lawrence", hint: "Hunger" },
    { word: "Emma Watson", hint: "Hermione" },
    { word: "Emma Stone", hint: "La" },
    { word: "Angelina Jolie", hint: "Lara" },
    { word: "Margot Robbie", hint: "Harley" },
    { word: "Gal Gadot", hint: "Wonder" },
    { word: "Zendaya", hint: "Spider" },
    { word: "Tom Holland", hint: "Spider" },
    { word: "Henry Cavill", hint: "Superman" },
    { word: "Vin Diesel", hint: "Furious" },
    { word: "Kim Kardashian", hint: "Reality" },
    { word: "Elon Musk", hint: "Tesla" },
    { word: "Jeff Bezos", hint: "Amazon" },
    { word: "Bill Gates", hint: "Microsoft" },
    { word: "Mark Zuckerberg", hint: "Facebook" },
    { word: "Steve Jobs", hint: "Apple" },
    { word: "Adele", hint: "Hello" },
    { word: "Ed Sheeran", hint: "Shape" },
    { word: "Bruno Mars", hint: "Uptown" },
    { word: "Drake", hint: "Hotline" },
    { word: "Eminem", hint: "Rap" },
    { word: "Kanye West", hint: "Yeezy" },
    { word: "Jay Z", hint: "Empire" },
    { word: "Cardi B", hint: "Okurrr" },
    { word: "Megan Thee Stallion", hint: "Hot" },
    { word: "Post Malone", hint: "Circles" },
    { word: "Travis Scott", hint: "Astroworld" },
    { word: "Lil Nas X", hint: "Town" },
    { word: "Doja Cat", hint: "Say" },
    { word: "Olivia Rodrigo", hint: "Driver" },
    { word: "Ryan Reynolds", hint: "Deadpool" },
    { word: "Chris Hemsworth", hint: "Thor" },
    { word: "Chris Pratt", hint: "Guardians" },
    { word: "Tom Hardy", hint: "Venom" },
    { word: "Jason Momoa", hint: "Aquaman" },
    { word: "Keanu Reeves", hint: "Matrix" },
    { word: "Samuel L Jackson", hint: "Fury" },
    { word: "Morgan Freeman", hint: "Narrador" },
    { word: "Denzel Washington", hint: "Training" },
    { word: "Matt Damon", hint: "Bourne" },
    { word: "George Clooney", hint: "Ocean" },
    { word: "Ryan Gosling", hint: "Drive" },
    { word: "Jake Gyllenhaal", hint: "Donnie" },
    { word: "Christian Bale", hint: "Batman" },
    { word: "Hugh Jackman", hint: "Wolverine" },
    { word: "Benedict Cumberbatch", hint: "Strange" },
    { word: "Paul Rudd", hint: "Ant" },
    { word: "Mark Ruffalo", hint: "Hulk" },
    { word: "Jeremy Renner", hint: "Hawkeye" },
    { word: "Sebastian Stan", hint: "Winter" },
    { word: "Anthony Mackie", hint: "Falcon" },
    { word: "Chadwick Boseman", hint: "Panther" },
    { word: "Brie Larson", hint: "Captain" },
    { word: "Elizabeth Olsen", hint: "Witch" },
    { word: "Natalie Portman", hint: "Black" },
    { word: "Anne Hathaway", hint: "Princess" },
    { word: "Sandra Bullock", hint: "Gravity" },
    { word: "Julia Roberts", hint: "Pretty" },
    { word: "Meryl Streep", hint: "Devil" },
    { word: "Charlize Theron", hint: "Mad" },
    { word: "Nicole Kidman", hint: "Big" },
    { word: "Penélope Cruz", hint: "Española" },
    { word: "Salma Hayek", hint: "Mexicana" },
    { word: "Cameron Diaz", hint: "Mask" },
    { word: "Drew Barrymore", hint: "Ever" },
    { word: "Reese Witherspoon", hint: "Legally" },
    { word: "Kate Winslet", hint: "Rose" },
    { word: "Amy Adams", hint: "Arrival" },
    { word: "Kristen Stewart", hint: "Twilight" },
    { word: "Robert Pattinson", hint: "Batman" },
    { word: "Daniel Radcliffe", hint: "Potter" },
    { word: "Rupert Grint", hint: "Ron" },
    { word: "Lionel Messi", hint: "Argentina" },
    { word: "Cristiano Ronaldo", hint: "Portugal" },
    { word: "Neymar Jr", hint: "Brasil" },
    { word: "Kylian Mbappé", hint: "Francia" },
    { word: "Erling Haaland", hint: "Noruega" },
    { word: "Mohamed Salah", hint: "Egipto" },
    { word: "Kevin De Bruyne", hint: "Bélgica" },
    { word: "Luka Modric", hint: "Croacia" },
    { word: "Sergio Ramos", hint: "España" },
    { word: "Gerard Piqué", hint: "Barcelona" },
    { word: "Zlatan Ibrahimovic", hint: "Suecia" },
    { word: "Luis Suárez", hint: "Uruguay" },
    { word: "Sergio Agüero", hint: "Kun" },
    { word: "Edinson Cavani", hint: "Matador" },
    { word: "James Rodríguez", hint: "Colombia" },
    { word: "Radamel Falcao", hint: "Tigre" },
    { word: "Alexis Sánchez", hint: "Chile" },
    { word: "Arturo Vidal", hint: "Rey" },
    { word: "Paolo Guerrero", hint: "Perú" },
    { word: "Jefferson Farfán", hint: "Foquita" },
    { word: "Claudio Pizarro", hint: "Bomber" },
    { word: "Gianluca Lapadula", hint: "Italia" },
    { word: "André Carrillo", hint: "Culebra" },
    { word: "Christian Cueva", hint: "Aladino" },
    { word: "Renato Tapia", hint: "Cabezón" },
    { word: "Pedro Gallese", hint: "Pulpo" },

    // Navidad (mantener todas, son conocidas en Perú)
    { word: "Santa Claus", hint: "Barba" },
    { word: "Papá Noel", hint: "Trineo" },
    { word: "Árbol", hint: "Pino" },
    { word: "Regalos", hint: "Papel" },
    { word: "Nieve", hint: "Blanca" },
    { word: "Estrella", hint: "Punta" },
    { word: "Corona", hint: "Puerta" },
    { word: "Velas", hint: "Mecha" },
    { word: "Campanas", hint: "Repique" },
    { word: "Villancicos", hint: "Coro" },
    { word: "Trineo", hint: "Madera" },
    { word: "Renos", hint: "Cuernos" },
    { word: "Calcetín", hint: "Chimenea" },
    { word: "Chimenea", hint: "Hollín" },
    { word: "Galletas", hint: "Leche" },
    { word: "Jengibre", hint: "Hombre" },
    { word: "Bastón", hint: "Rayado" },
    { word: "Luces", hint: "Series" },
    { word: "Foco", hint: "Intermitente" },
    { word: "Adornos", hint: "Esferas" },
    { word: "Esferas", hint: "Vidrio" },
    { word: "Bolas", hint: "Brillantes" },
    { word: "Escarcha", hint: "Spray" },
    { word: "Algodón", hint: "Blanco" },
    { word: "Musgo", hint: "Nacimiento" },
    { word: "Nacimiento", hint: "Pesebre" },
    { word: "Belén", hint: "Portal" },
    { word: "José", hint: "Carpintero" },
    { word: "María", hint: "Madre" },
    { word: "Jesús", hint: "Niño" },
    { word: "Ángel", hint: "Alas" },
    { word: "Pastor", hint: "Ovejas" },
    { word: "Reyes Magos", hint: "Tres" },
    { word: "Melchor", hint: "Rey" },
    { word: "Gaspar", hint: "Rey" },
    { word: "Baltazar", hint: "Rey" },
    { word: "Camello", hint: "Joroba" },
    { word: "Oro", hint: "Metal" },
    { word: "Incienso", hint: "Resina" },
    { word: "Mirra", hint: "Perfume" },
    { word: "Pavo", hint: "Ave" },
    { word: "Jamón", hint: "Cerdo" },
    { word: "Lechón", hint: "Asado" },
    { word: "Tamales", hint: "Maíz" },
    { word: "Ponche", hint: "Caliente" },
    { word: "Champán", hint: "Burbujas" },
    { word: "Chocolate", hint: "Caliente" },
    { word: "Panetón", hint: "Italia" },
    { word: "Turrón", hint: "Almendra" },
    { word: "Nueces", hint: "Cáscara" },
    { word: "Almendras", hint: "Fruto" },
    { word: "Pasas", hint: "Uvas" },
    { word: "Higo", hint: "Secos" },
    { word: "Manzanas", hint: "Dulce" },
    { word: "Naranjas", hint: "Mandarina" },
    { word: "Mandarinas", hint: "Cítrico" },
    { word: "Piña", hint: "Corona" },
    { word: "Uvas", hint: "Doce" },
    { word: "Granada", hint: "Semillas" },
    { word: "Ensalada", hint: "Manzana" },
    { word: "Puré", hint: "Cremoso" },
    { word: "Medianoche", hint: "Doce" },
    { word: "Año Nuevo", hint: "Cuenta" },
    { word: "Misa de gallo", hint: "Nocturna" },
    { word: "Aguinaldo", hint: "Bono" },
    { word: "Carta", hint: "Deseos" },
    { word: "Lista", hint: "Buenos" },
    { word: "Niño bueno", hint: "Comportamiento" },
    { word: "Carbón", hint: "Negro" },
    { word: "Juguetes", hint: "Niños" },
    { word: "Muñeca", hint: "Brazos" },
    { word: "Carrito", hint: "Ruedas" },
    { word: "Pelota", hint: "Esférica" },
    { word: "Bicicleta", hint: "Pedales" },
    { word: "Patines", hint: "Ruedas" },
    { word: "Videojuego", hint: "Consola" },
    { word: "Tablet", hint: "Pantalla" },
    { word: "Celular", hint: "Teléfono" },
    { word: "Auriculares", hint: "Oídos" },
    { word: "Ropa", hint: "Vestir" },
    { word: "Chompa", hint: "Lana" },
    { word: "Bufanda", hint: "Cuello" },
    { word: "Guantes", hint: "Dedos" },
    { word: "Gorro", hint: "Cabeza" },
    { word: "Abrigo", hint: "Largo" },
    { word: "Casaca", hint: "Zipper" },
    { word: "Botas", hint: "Altas" },
    { word: "Medias", hint: "Piernas" },
    { word: "Pijama", hint: "Dormir" },
    { word: "Pantuflas", hint: "Casa" },
    { word: "Perfume", hint: "Fragancia" },
    { word: "Reloj", hint: "Muñeca" },
    { word: "Collar", hint: "Cuello" },
    { word: "Pulsera", hint: "Muñeca" },
    { word: "Aretes", hint: "Orejas" },
    { word: "Anillo", hint: "Dedo" },
    { word: "Billetera", hint: "Dinero" },
    { word: "Bolso", hint: "Correa" },
    { word: "Mochila", hint: "Espalda" },
    { word: "Maleta", hint: "Viaje" },
    { word: "Libro", hint: "Páginas" },
    { word: "Calendario", hint: "Fechas" },
    { word: "Tarjeta", hint: "Cartón" },
    { word: "Sobre", hint: "Carta" },
    { word: "Paquete", hint: "Caja" },
    { word: "Caja", hint: "Envoltorio" },
    { word: "Moño", hint: "Lazo" },
    { word: "Cinta", hint: "Decorativa" },
    { word: "Papel", hint: "Regalo" },
    { word: "Etiqueta", hint: "Nombre" },
    { word: "Dedicatoria", hint: "Mensaje" },
    { word: "Cinta adhesiva", hint: "Pegar" },
    { word: "Tijeras", hint: "Cortar" },
    { word: "Familia", hint: "Reunión" },
    { word: "Abuelos", hint: "Mayores" },
    { word: "Padres", hint: "Mamá" },
    { word: "Hijos", hint: "Niños" },
    { word: "Hermanos", hint: "Familia" },
    { word: "Primos", hint: "Parientes" },
    { word: "Tíos", hint: "Familia" },
    { word: "Sobrinos", hint: "Pequeños" },
    { word: "Nietos", hint: "Descendientes" },
    { word: "Cena", hint: "Mesa" },
    { word: "Abrazo", hint: "Brazos" },
    { word: "Beso", hint: "Labios" },
    { word: "Amor", hint: "Sentimiento" },
    { word: "Paz", hint: "Paloma" },
    { word: "Alegría", hint: "Felicidad" },
    { word: "Esperanza", hint: "Verde" },
    { word: "Fe", hint: "Creencia" },
    { word: "Caridad", hint: "Generosidad" },
    { word: "Humildad", hint: "Sencillez" },

    // Comida (mantener la mayoría, ajustar algunas)
    { word: "Pizza", hint: "Horno" },
    { word: "Hamburguesa", hint: "Pan" },
    { word: "Tacos", hint: "Tortilla" },
    { word: "Sushi", hint: "Arroz" },
    { word: "Pasta", hint: "Trigo" },
    { word: "Arroz", hint: "Grano" },
    { word: "Pollo", hint: "Ave" },
    { word: "Carne", hint: "Res" },
    { word: "Pescado", hint: "Escamas" },
    { word: "Camarones", hint: "Cola" },
    { word: "Ensalada", hint: "Lechuga" },
    { word: "Sopa", hint: "Caldo" },
    { word: "Pan", hint: "Levadura" },
    { word: "Empanadas", hint: "Doblez" },
    { word: "Tamales", hint: "Hoja" },
    { word: "Hot dog", hint: "Salchicha" },
    { word: "Sandwich", hint: "Rebanadas" },
    { word: "Salchicha", hint: "Frankfurter" },
    { word: "Jamón", hint: "Cerdo" },
    { word: "Queso", hint: "Leche" },
    { word: "Crema", hint: "Ácida" },
    { word: "Mantequilla", hint: "Amarilla" },
    { word: "Yogurt", hint: "Fermentado" },
    { word: "Leche", hint: "Vaca" },
    { word: "Huevo", hint: "Gallina" },
    { word: "Frijoles", hint: "Legumbre" },
    { word: "Lentejas", hint: "Pequeñas" },
    { word: "Palta", hint: "Verde" },
    { word: "Guacamole", hint: "Molcajete" },
    { word: "Salsa", hint: "Picante" },
    { word: "Mayonesa", hint: "Emulsión" },
    { word: "Ketchup", hint: "Tomate" },
    { word: "Mostaza", hint: "Amarilla" },
    { word: "Ajo", hint: "Diente" },
    { word: "Cebolla", hint: "Capas" },
    { word: "Tomate", hint: "Rojo" },
    { word: "Ají", hint: "Picante" },
    { word: "Rocoto", hint: "Relleno" },
    { word: "Papa", hint: "Tubérculo" },
    { word: "Camote", hint: "Dulce" },
    { word: "Yuca", hint: "Mandioca" },
    { word: "Zanahoria", hint: "Naranja" },
    { word: "Espinaca", hint: "Verde" },
    { word: "Lechuga", hint: "Hojas" },
    { word: "Brócoli", hint: "Arbolito" },
    { word: "Pimiento", hint: "Campana" },
    { word: "Apio", hint: "Tallo" },
    { word: "Cilantro", hint: "Aromático" },
    { word: "Perejil", hint: "Rizado" },
    { word: "Laurel", hint: "Hoja" },
    { word: "Hierbabuena", hint: "Refrescante" },
    { word: "Manzana", hint: "Eva" },
    { word: "Pera", hint: "Forma" },
    { word: "Plátano", hint: "Potasio" },
    { word: "Naranja", hint: "Cítrico" },
    { word: "Mandarina", hint: "Pequeña" },
    { word: "Limón", hint: "Ácido" },
    { word: "Toronja", hint: "Amarga" },
    { word: "Uva", hint: "Racimo" },
    { word: "Fresa", hint: "Semillas" },
    { word: "Frambuesa", hint: "Pequeña" },
    { word: "Mora", hint: "Oscura" },
    { word: "Arándano", hint: "Azul" },
    { word: "Cereza", hint: "Hueso" },
    { word: "Durazno", hint: "Peludo" },
    { word: "Mango", hint: "Tropical" },
    { word: "Piña", hint: "Espinas" },
    { word: "Papaya", hint: "Naranja" },
    { word: "Sandía", hint: "Semillas" },
    { word: "Melón", hint: "Dulce" },
    { word: "Kiwi", hint: "Verde" },
    { word: "Coco", hint: "Peludo" },
    { word: "Maracuyá", hint: "Pasión" },
    { word: "Guayaba", hint: "Rosa" },
    { word: "Higo", hint: "Dulce" },
    { word: "Ciruela", hint: "Pasa" },
    { word: "Lúcuma", hint: "Helado" },
    { word: "Chirimoya", hint: "Escamas" },
    { word: "Granadilla", hint: "Pepas" },
    { word: "Tuna", hint: "Espinas" },
    { word: "Chocolate", hint: "Cacao" },
    { word: "Vainilla", hint: "Extracto" },
    { word: "Café", hint: "Grano" },
    { word: "Té", hint: "Hojas" },
    { word: "Gaseosa", hint: "Gas" },
    { word: "Jugo", hint: "Exprimido" },
    { word: "Agua", hint: "Hidratación" },
    { word: "Cerveza", hint: "Lúpulo" },
    { word: "Vino", hint: "Uva" },
    { word: "Pisco", hint: "Perú" },
    { word: "Ron", hint: "Caña" },
    { word: "Chicha", hint: "Morada" },
    { word: "Inca Kola", hint: "Amarilla" },
    { word: "Emoliente", hint: "Caliente" },
    { word: "Limonada", hint: "Cítrico" },
    { word: "Naranjada", hint: "Naranja" },
    { word: "Cappuccino", hint: "Espuma" },
    { word: "Helado", hint: "Congelado" },
    { word: "Paleta", hint: "Palo" },
    { word: "Flan", hint: "Caramelo" },
    { word: "Gelatina", hint: "Grenetina" },
    { word: "Torta", hint: "Betún" },
    { word: "Pie", hint: "Corteza" },
    { word: "Galletas", hint: "Crujientes" },
    { word: "Donas", hint: "Agujero" },
    { word: "Churros", hint: "Azúcar" },
    { word: "Picarones", hint: "Miel" },
    { word: "Alfajor", hint: "Manjar" },
    { word: "Suspiro", hint: "Limeño" },
    { word: "Mazamorra", hint: "Morada" },
    { word: "Arroz con leche", hint: "Canela" },
    { word: "Ceviche", hint: "Limón" },
    { word: "Lomo saltado", hint: "Wok" },
    { word: "Ají de gallina", hint: "Amarillo" },
    { word: "Causa", hint: "Papa" },
    { word: "Anticuchos", hint: "Corazón" },
    { word: "Pachamanca", hint: "Tierra" },
    { word: "Tacu tacu", hint: "Frito" },
    { word: "Carapulcra", hint: "Papa" },
    { word: "Seco", hint: "Cilantro" },
    { word: "Arroz chaufa", hint: "Chino" },
    { word: "Tallarín", hint: "Saltado" },
    { word: "Wantán", hint: "Sopa" },
    { word: "Pollo a la brasa", hint: "Carbón" },
    { word: "Salchipapa", hint: "Papas" },
    { word: "Butifarra", hint: "Pan" },
    { word: "Chicharrón", hint: "Cerdo" },
    { word: "Rocoto relleno", hint: "Picante" },

    // Hollywood (mantener, son conocidas globalmente)
    { word: "Oscar", hint: "Estatuilla" },
    { word: "Titanic", hint: "Barco" },
    { word: "Avatar", hint: "Azul" },
    { word: "Avengers", hint: "Equipo" },
    { word: "Iron Man", hint: "Armadura" },
    { word: "Spider Man", hint: "Telaraña" },
    { word: "Batman", hint: "Murciélago" },
    { word: "Superman", hint: "Capa" },
    { word: "Wonder Woman", hint: "Lazo" },
    { word: "Harry Potter", hint: "Varita" },
    { word: "Star Wars", hint: "Sable" },
    { word: "Matrix", hint: "Píldora" },
    { word: "Terminator", hint: "Robot" },
    { word: "Jurassic Park", hint: "Dinosaurios" },
    { word: "Tiburón", hint: "Aleta" },
    { word: "ET", hint: "Extraterrestre" },
    { word: "Indiana Jones", hint: "Látigo" },
    { word: "Rocky", hint: "Boxeo" },
    { word: "Rambo", hint: "Cinta" },
    { word: "Forrest Gump", hint: "Pluma" },
    { word: "Gladiador", hint: "Coliseo" },
    { word: "Troya", hint: "Caballo" },
    { word: "300", hint: "Espartanos" },
    { word: "Corazón valiente", hint: "Escocia" },
    { word: "Shrek", hint: "Ogro" },
    { word: "Toy Story", hint: "Juguetes" },
    { word: "Buscando a Nemo", hint: "Pez" },
    { word: "Frozen", hint: "Hielo" },
    { word: "Moana", hint: "Océano" },
    { word: "Coco", hint: "Guitarra" },
    { word: "Up", hint: "Globos" },
    { word: "Wall E", hint: "Robot" },
    { word: "Monsters Inc", hint: "Puerta" },
    { word: "Cars", hint: "Rayo" },
    { word: "Ratatouille", hint: "Rata" },
    { word: "Valiente", hint: "Arco" },
    { word: "Intensamente", hint: "Emociones" },
    { word: "El Rey León", hint: "Simba" },
    { word: "Aladino", hint: "Lámpara" },
    { word: "La Bella y la Bestia", hint: "Rosa" },
    { word: "Mulan", hint: "Dragón" },
    { word: "Pocahontas", hint: "Viento" },
    { word: "Hércules", hint: "Zeus" },
    { word: "Tarzán", hint: "Liana" },
    { word: "Dumbo", hint: "Orejas" },
    { word: "Bambi", hint: "Cervatillo" },
    { word: "Pinocho", hint: "Nariz" },
    { word: "Cenicienta", hint: "Zapatilla" },
    { word: "La Bella Durmiente", hint: "Espina" },
    { word: "Blanca Nieves", hint: "Manzana" },
    { word: "La Sirenita", hint: "Voz" },
    { word: "Enredados", hint: "Cabello" },
    { word: "Zootopia", hint: "Animales" },
    { word: "Big Hero 6", hint: "Baymax" },
    { word: "Ralph el demoledor", hint: "Videojuego" },
    { word: "Encanto", hint: "Casita" },
    { word: "Soul", hint: "Piano" },
    { word: "Los Increíbles", hint: "Familia" },
    { word: "Mi villano favorito", hint: "Minions" },
    { word: "Kung Fu Panda", hint: "Oso" },
    { word: "Madagascar", hint: "Cebra" },
    { word: "La Era de Hielo", hint: "Bellota" },
    { word: "Cómo entrenar a tu dragón", hint: "Dragón" },
    { word: "El Gato con Botas", hint: "Gato" },
    { word: "Trolls", hint: "Cabello" },
    { word: "Minions", hint: "Amarillo" },
    { word: "Río", hint: "Guacamaya" },
    { word: "Snoopy", hint: "Beagle" },
    { word: "Garfield", hint: "Lasaña" },
    { word: "Scooby Doo", hint: "Misterio" },
    { word: "Tom y Jerry", hint: "Persecución" },
    { word: "Mickey Mouse", hint: "Orejas" },
    { word: "Pato Donald", hint: "Pato" },
    { word: "Goofy", hint: "Torpe" },
    { word: "Pluto", hint: "Perro" },
    { word: "Minnie", hint: "Moño" },
    { word: "Chip y Dale", hint: "Ardillas" },
    { word: "Winnie Pooh", hint: "Miel" },
    { word: "Tigger", hint: "Rebote" },
    { word: "Dumbledore", hint: "Director" },
    { word: "Voldemort", hint: "Calvo" },
    { word: "Hermione", hint: "Inteligente" },
    { word: "Ron", hint: "Pelirrojo" },
    { word: "Hagrid", hint: "Gigante" },
    { word: "Snape", hint: "Poción" },
    { word: "Dobby", hint: "Elfo" },
    { word: "Hedwig", hint: "Lechuza" },
    { word: "Hogwarts", hint: "Castillo" },
    { word: "Gryffindor", hint: "León" },
    { word: "Slytherin", hint: "Serpiente" },
    { word: "Quidditch", hint: "Escoba" },
    { word: "Luke Skywalker", hint: "Granjero" },
    { word: "Darth Vader", hint: "Respiración" },
    { word: "Yoda", hint: "Verde" },
    { word: "Chewbacca", hint: "Peludo" },
    { word: "Han Solo", hint: "Contrabandista" },
    { word: "Leia", hint: "Princesa" },
    { word: "R2D2", hint: "Beep" },
    { word: "C3PO", hint: "Protocolo" },
    { word: "Obi Wan", hint: "Maestro" },
    { word: "Neo", hint: "Elegido" },
    { word: "Trinity", hint: "Cuero" },
    { word: "Morpheus", hint: "Gafas" },
    { word: "Woody", hint: "Sheriff" },
    { word: "Buzz Lightyear", hint: "Espacio" },
    { word: "Jessie", hint: "Vaquera" },
    { word: "Rex", hint: "Nervioso" },
    { word: "Elsa", hint: "Nieve" },
    { word: "Anna", hint: "Hermana" },
    { word: "Olaf", hint: "Muñeco" },
    { word: "Simba", hint: "Cachorro" },
    { word: "Mufasa", hint: "Padre" },
    { word: "Scar", hint: "Cicatriz" },
    { word: "Nala", hint: "Leona" },
    { word: "Timón", hint: "Suricata" },
    { word: "Pumba", hint: "Jabalí" },
    { word: "Genio", hint: "Tres" },
    { word: "Jasmín", hint: "Tigre" },

    // Marcas (mantener las globales, ajustar regionales)
    { word: "Nike", hint: "Swoosh" },
    { word: "Adidas", hint: "Tres" },
    { word: "Puma", hint: "Felino" },
    { word: "Apple", hint: "Manzana" },
    { word: "Samsung", hint: "Galaxy" },
    { word: "Huawei", hint: "China" },
    { word: "Xiaomi", hint: "Mi" },
    { word: "Sony", hint: "PlayStation" },
    { word: "LG", hint: "Sonrisa" },
    { word: "Microsoft", hint: "Ventanas" },
    { word: "Google", hint: "G" },
    { word: "Facebook", hint: "F" },
    { word: "Instagram", hint: "Cámara" },
    { word: "Twitter", hint: "Pájaro" },
    { word: "TikTok", hint: "Musical" },
    { word: "YouTube", hint: "Play" },
    { word: "WhatsApp", hint: "Bocadillo" },
    { word: "Amazon", hint: "Sonrisa" },
    { word: "Netflix", hint: "N" },
    { word: "Disney", hint: "Ratón" },
    { word: "Spotify", hint: "Verde" },
    { word: "Uber", hint: "U" },
    { word: "Visa", hint: "Azul" },
    { word: "Mastercard", hint: "Círculos" },
    { word: "Coca Cola", hint: "Roja" },
    { word: "Pepsi", hint: "Esfera" },
    { word: "Sprite", hint: "Verde" },
    { word: "Fanta", hint: "Naranja" },
    { word: "Inca Kola", hint: "Amarilla" },
    { word: "Red Bull", hint: "Toros" },
    { word: "Gatorade", hint: "Rayo" },
    { word: "Nestlé", hint: "Nido" },
    { word: "Gloria", hint: "Leche" },
    { word: "Laive", hint: "Yogurt" },
    { word: "Donofrio", hint: "Helado" },
    { word: "Sublime", hint: "Chocolate" },
    { word: "Oreo", hint: "Galleta" },
    { word: "Pringles", hint: "Bigote" },
    { word: "Doritos", hint: "Triángulo" },
    { word: "Lay's", hint: "Papa" },
    { word: "McDonald's", hint: "M" },
    { word: "Burger King", hint: "Rey" },
    { word: "KFC", hint: "Coronel" },
    { word: "Starbucks", hint: "Sirena" },
    { word: "Bembos", hint: "Perú" },
    { word: "Pardos", hint: "Pollo" },
    { word: "Norky's", hint: "Pollería" },
    { word: "Roky's", hint: "Pollo" },
    { word: "Toyota", hint: "T" },
    { word: "Honda", hint: "H" },
    { word: "Nissan", hint: "Círculo" },
    { word: "Hyundai", hint: "H" },
    { word: "Kia", hint: "Óvalo" },
    { word: "Ford", hint: "Óvalo" },
    { word: "Chevrolet", hint: "Cruz" },
    { word: "BMW", hint: "Hélice" },
    { word: "Mercedes", hint: "Estrella" },
    { word: "Audi", hint: "Aros" },
    { word: "Volkswagen", hint: "VW" },
    { word: "Ferrari", hint: "Caballo" },
    { word: "Lamborghini", hint: "Toro" },
    { word: "Zara", hint: "Z" },
    { word: "H&M", hint: "HM" },
    { word: "Nike", hint: "Swoosh" },
    { word: "Adidas", hint: "Rayas" },
    { word: "Gucci", hint: "GG" },
    { word: "Louis Vuitton", hint: "LV" },
    { word: "Prada", hint: "Triángulo" },
    { word: "Chanel", hint: "CC" },
    { word: "Rolex", hint: "Corona" },
    { word: "Casio", hint: "Digital" },
    { word: "Ikea", hint: "Azul" },
    { word: "Walmart", hint: "W" },
    { word: "Plaza Vea", hint: "Plaza" },
    { word: "Tottus", hint: "Supermercado" },
    { word: "Metro", hint: "Wong" },
    { word: "Sodimac", hint: "Construcción" },
    { word: "Promart", hint: "Hogar" },
    { word: "Ripley", hint: "Tienda" },
    { word: "Saga Falabella", hint: "Tienda" },
    { word: "Oechsle", hint: "Tienda" },
    { word: "Paris", hint: "Tienda" },
    { word: "Real Plaza", hint: "Mall" },
    { word: "Jockey Plaza", hint: "Centro" },
    { word: "Larcomar", hint: "Vista" },
    { word: "Panasonic", hint: "Ideas" },
    { word: "Philips", hint: "Escudo" },
    { word: "Gillette", hint: "Navaja" },
    { word: "Colgate", hint: "Rojo" },
    { word: "Oral B", hint: "Cepillo" },
    { word: "Nivea", hint: "Azul" },
    { word: "Dove", hint: "Paloma" },
    { word: "Pantene", hint: "P" },
    { word: "Head & Shoulders", hint: "Caspa" },

    // Lugares (mantener conocidos, eliminar muy específicos de USA)
    { word: "París", hint: "Torre" },
    { word: "Londres", hint: "Reloj" },
    { word: "Roma", hint: "Coliseo" },
    { word: "Tokio", hint: "Fuji" },
    { word: "Nueva York", hint: "Manzana" },
    { word: "Los Ángeles", hint: "Hollywood" },
    { word: "Miami", hint: "Playa" },
    { word: "Las Vegas", hint: "Casino" },
    { word: "San Francisco", hint: "Puente" },
    { word: "Washington", hint: "Capital" },
    { word: "México", hint: "Azteca" },
    { word: "Cancún", hint: "Turquesa" },
    { word: "Buenos Aires", hint: "Tango" },
    { word: "Río de Janeiro", hint: "Cristo" },
    { word: "Lima", hint: "Pisco" },
    { word: "Cusco", hint: "Ombligo" },
    { word: "Machu Picchu", hint: "Ruinas" },
    { word: "Arequipa", hint: "Blanca" },
    { word: "Trujillo", hint: "Primavera" },
    { word: "Chiclayo", hint: "Amistad" },
    { word: "Piura", hint: "Calor" },
    { word: "Iquitos", hint: "Selva" },
    { word: "Puno", hint: "Titicaca" },
    { word: "Nazca", hint: "Líneas" },
    { word: "Paracas", hint: "Reserva" },
    { word: "Huacachina", hint: "Oasis" },
    { word: "Máncora", hint: "Surf" },
    { word: "Ayacucho", hint: "Retablos" },
    { word: "Huaraz", hint: "Montañas" },
    { word: "Tarapoto", hint: "Palmeras" },
    { word: "Santiago", hint: "Andes" },
    { word: "Bogotá", hint: "Esmeraldas" },
    { word: "Madrid", hint: "Oso" },
    { word: "Barcelona", hint: "Sagrada" },
    { word: "Berlín", hint: "Muro" },
    { word: "Ámsterdam", hint: "Canales" },
    { word: "Viena", hint: "Vals" },
    { word: "Praga", hint: "Puente" },
    { word: "Milán", hint: "Moda" },
    { word: "Venecia", hint: "Góndolas" },
    { word: "Atenas", hint: "Partenón" },
    { word: "Estambul", hint: "Bósforo" },
    { word: "El Cairo", hint: "Pirámides" },
    { word: "Marrakech", hint: "Medina" },
    { word: "Dubái", hint: "Rascacielos" },
    { word: "Bombay", hint: "Bollywood" },
    { word: "Bangkok", hint: "Templos" },
    { word: "Pekín", hint: "Forbidden" },
    { word: "Shanghái", hint: "Bund" },
    { word: "Hong Kong", hint: "Victoria" },
    { word: "Sídney", hint: "Ópera" },
    { word: "Melbourne", hint: "Australia" },
    { word: "Auckland", hint: "Nueva" },
    { word: "Toronto", hint: "Canadá" },
    { word: "Montreal", hint: "Francés" },
    { word: "Vancouver", hint: "Costa" },

    // Animales (mantener todos, son universales)
    { word: "Perro", hint: "Ladrido" },
    { word: "Gato", hint: "Maullido" },
    { word: "Ratón", hint: "Roedor" },
    { word: "Elefante", hint: "Trompa" },
    { word: "León", hint: "Melena" },
    { word: "Tigre", hint: "Rayas" },
    { word: "Oso", hint: "Miel" },
    { word: "Panda", hint: "Bambú" },
    { word: "Canguro", hint: "Marsupio" },
    { word: "Jirafa", hint: "Cuello" },
    { word: "Cebra", hint: "Rayas" },
    { word: "Hipopótamo", hint: "Agua" },
    { word: "Rinoceronte", hint: "Cuerno" },
    { word: "Camello", hint: "Joroba" },
    { word: "Llama", hint: "Escupir" },
    { word: "Alpaca", hint: "Lana" },
    { word: "Vicuña", hint: "Andina" },
    { word: "Mono", hint: "Plátano" },
    { word: "Gorila", hint: "Pecho" },
    { word: "Lobo", hint: "Aullido" },
    { word: "Zorro", hint: "Cola" },
    { word: "Conejo", hint: "Orejas" },
    { word: "Cuy", hint: "Chillido" },
    { word: "Caballo", hint: "Relincho" },
    { word: "Burro", hint: "Rebuzno" },
    { word: "Vaca", hint: "Mugido" },
    { word: "Toro", hint: "Cuernos" },
    { word: "Cerdo", hint: "Gruñido" },
    { word: "Oveja", hint: "Balido" },
    { word: "Cabra", hint: "Barbilla" },
    { word: "Gallina", hint: "Cacareo" },
    { word: "Gallo", hint: "Cresta" },
    { word: "Pato", hint: "Cuac" },
    { word: "Pavo", hint: "Gluglú" },
    { word: "Paloma", hint: "Zureo" },
    { word: "Loro", hint: "Habla" },
    { word: "Águila", hint: "Garras" },
    { word: "Cóndor", hint: "Andino" },
    { word: "Búho", hint: "Nocturno" },
    { word: "Gaviota", hint: "Costera" },
    { word: "Pelícano", hint: "Bolsa" },
    { word: "Flamenco", hint: "Rosa" },
    { word: "Pingüino", hint: "Frac" },
    { word: "Colibrí", hint: "Suspensión" },
    { word: "Golondrina", hint: "Migración" },
    { word: "Gorrión", hint: "Común" },
    { word: "Cocodrilo", hint: "Lagarto" },
    { word: "Tortuga", hint: "Caparazón" },
    { word: "Serpiente", hint: "Reptar" },
    { word: "Iguana", hint: "Cresta" },
    { word: "Rana", hint: "Salto" },
    { word: "Sapo", hint: "Verruga" },
    { word: "Tiburón", hint: "Aleta" },
    { word: "Ballena", hint: "Gigante" },
    { word: "Delfín", hint: "Silbido" },
    { word: "Lobo marino", hint: "Ladrido" },
    { word: "Nutria", hint: "Juguetona" },
    { word: "Pez", hint: "Escamas" },
    { word: "Anchoveta", hint: "Pequeña" },
    { word: "Bonito", hint: "Mar" },
    { word: "Atún", hint: "Lata" },
    { word: "Pulpo", hint: "Ocho" },
    { word: "Calamar", hint: "Tinta" },
    { word: "Medusa", hint: "Tentáculos" },
    { word: "Cangrejo", hint: "Pinzas" },
    { word: "Langostino", hint: "Grande" },
    { word: "Caracol", hint: "Espiral" },
    { word: "Hormiga", hint: "Fila" },
    { word: "Abeja", hint: "Panal" },
    { word: "Avispa", hint: "Aguijón" },
    { word: "Mosca", hint: "Zumbido" },
    { word: "Mosquito", hint: "Picadura" },
    { word: "Mariposa", hint: "Alas" },
    { word: "Libélula", hint: "Cuatro" },
    { word: "Escarabajo", hint: "Caparazón" },
    { word: "Mariquita", hint: "Puntos" },
    { word: "Grillo", hint: "Chirriado" },
    { word: "Saltamontes", hint: "Salto" },
    { word: "Araña", hint: "Ocho" },
    { word: "Tarántula", hint: "Peluda" },
    { word: "Escorpión", hint: "Aguijón" },

    // Deportes (mantener conocidos en Perú)
    { word: "Fútbol", hint: "Gol" },
    { word: "Vóley", hint: "Red" },
    { word: "Básquet", hint: "Canasta" },
    { word: "Tenis", hint: "Raqueta" },
    { word: "Natación", hint: "Piscina" },
    { word: "Atletismo", hint: "Pista" },
    { word: "Boxeo", hint: "Ring" },
    { word: "Karate", hint: "Kata" },
    { word: "Judo", hint: "Tatami" },
    { word: "Taekwondo", hint: "Patada" },
    { word: "Ciclismo", hint: "Pedal" },
    { word: "Surf", hint: "Tabla" },
    { word: "Skateboard", hint: "Patineta" },
    { word: "Gimnasia", hint: "Anillas" },
    { word: "Escalada", hint: "Pared" },
    { word: "Maratón", hint: "42" },
    { word: "Golf", hint: "Hoyo" },
    { word: "Rugby", hint: "Oval" },
    { word: "Béisbol", hint: "Base" },
    { word: "Pelota", hint: "Redonda" },
    { word: "Arco", hint: "Portería" },
    { word: "Gol", hint: "Anotación" },
    { word: "Penalti", hint: "Penal" },
    { word: "Córner", hint: "Esquina" },
    { word: "Árbitro", hint: "Silbato" },
    { word: "Tarjeta", hint: "Roja" },
    { word: "Offside", hint: "Fuera" },
    { word: "Pelotazo", hint: "Golpe" },
    { word: "Cabezazo", hint: "Cabeza" },
    { word: "Chilena", hint: "Bicicleta" },
    { word: "Tiro libre", hint: "Falta" },
    { word: "Portero", hint: "Guantes" },
    { word: "Defensa", hint: "Atrás" },
    { word: "Mediocampista", hint: "Centro" },
    { word: "Delantero", hint: "Adelante" },
    { word: "Capitán", hint: "Brazalete" },
    { word: "Hincha", hint: "Aficionado" },
    { word: "Barra", hint: "Tribuna" },
    { word: "Estadio", hint: "Cancha" },
    { word: "Mundial", hint: "Copa" },
    { word: "Champions", hint: "Europa" },
    { word: "Libertadores", hint: "América" },
    { word: "Clásico", hint: "Rival" },
    { word: "Derby", hint: "Ciudad" },
    { word: "Campeonato", hint: "Torneo" },
    { word: "Descenso", hint: "Bajar" },
    { word: "Ascenso", hint: "Subir" },
    { word: "Tabla", hint: "Posiciones" },
    { word: "Puntaje", hint: "Puntos" },
    { word: "Empate", hint: "Igualdad" },
    { word: "Victoria", hint: "Ganar" },
    { word: "Derrota", hint: "Perder" },

    // Picante (ajustar algunos términos)
    { word: "Stripper", hint: "Tubo" },
    { word: "Tanga", hint: "Hilo" },
    { word: "Lencería", hint: "Encaje" },
    { word: "Condón", hint: "Látex" },
    { word: "Beso", hint: "Lengua" },
    { word: "Orgasmo", hint: "Clímax" },
    { word: "Vibrador", hint: "Batería" },
    { word: "Esposas", hint: "Metal" },
    { word: "Látigo", hint: "Cuero" },
    { word: "Kamasutra", hint: "Manual" },
    { word: "Lubricante", hint: "Resbaloso" },
    { word: "Desnudo", hint: "Ropa" },
    { word: "Erótico", hint: "Sensual" },
    { word: "Prostituta", hint: "Pago" },
    { word: "Infidelidad", hint: "Cuernos" },
    { word: "Amante", hint: "Secreto" },
    { word: "Morbo", hint: "Curiosidad" },
    { word: "Fetiche", hint: "Obsesión" },
    { word: "Voyeur", hint: "Mirar" },
    { word: "Seducción", hint: "Conquista" },
    { word: "Coqueteo", hint: "Insinuación" },
    { word: "Ligue", hint: "Encuentro" },
    { word: "Aventura", hint: "Pasajera" },
    { word: "Hotel", hint: "Alojamiento" },
    { word: "Motel", hint: "Horas" },
    { word: "Sábanas", hint: "Tela" },
    { word: "Almohada", hint: "Cabeza" },
    { word: "Ducha", hint: "Agua" },
    { word: "Vela", hint: "Cera" },
    { word: "Copa", hint: "Vino" },
    { word: "Champán", hint: "Celebración" },
    { word: "Chocolate", hint: "Derretido" },
    { word: "Fresa", hint: "Fruta" },
    { word: "Labios", hint: "Boca" },
    { word: "Cuello", hint: "Garganta" },
    { word: "Perfume", hint: "Aroma" },
    { word: "Piel", hint: "Epidermis" },
    { word: "Beso", hint: "Contacto" },
    { word: "Abrazo", hint: "Brazos" },
    { word: "Caricia", hint: "Toque" },
    { word: "Placer", hint: "Gozo" },
    { word: "Pasión", hint: "Intenso" },
    { word: "Deseo", hint: "Anhelo" },
    { word: "Tentación", hint: "Provocación" },
    { word: "Prohibido", hint: "Tabú" },
    { word: "Secreto", hint: "Oculto" },
    { word: "Atrevido", hint: "Osado" },
    { word: "Ardiente", hint: "Fogoso" },
    { word: "Travieso", hint: "Pícaro" },
    { word: "Sensual", hint: "Provocativo" },
    { word: "Sexy", hint: "Atractivo" },
    { word: "Provocativo", hint: "Incitante" },
    { word: "Seductor", hint: "Encantador" },
    { word: "Irresistible", hint: "Magnético" },
    { word: "Delicioso", hint: "Sabroso" }
];

const categories = {
    all: wordsDatabase,
    fiesta: wordsDatabase.slice(0, 180),
    celebridades: wordsDatabase.slice(180, 360),
    navidad: wordsDatabase.slice(360, 500),
    comida: wordsDatabase.slice(500, 650),
    hollywood: wordsDatabase.slice(650, 770),
    marcas: wordsDatabase.slice(770, 890),
    lugares: wordsDatabase.slice(890, 970),
    animales: wordsDatabase.slice(970, 1070),
    deportes: wordsDatabase.slice(1070, 1130),
    picante: wordsDatabase.slice(1130, 1190)
};

function getRandomWord(category = 'all') {
    const categoryWords = categories[category] || categories.all;
    const randomIndex = Math.floor(Math.random() * categoryWords.length);
    return categoryWords[randomIndex];
}

function generateRoomCode() {
    const characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
    let code = '';
    for (let i = 0; i < 6; i++) {
        code += characters.charAt(Math.floor(Math.random() * characters.length));
    }
    return code;
}

function selectImpostors(players, impostorCount) {
    const shuffled = [...players].sort(() => Math.random() - 0.5);
    const impostorIds = shuffled.slice(0, impostorCount).map(p => p.id);
    return impostorIds;
}

module.exports = {
    getRandomWord,
    generateRoomCode,
    selectImpostors,
    categories: Object.keys(categories)
};