const categories = {
    fiesta: [
        { word: "Globo", hint: "Helio" },
        { word: "Confeti", hint: "Fragmentos" },
        { word: "Música", hint: "Decibeles" },
        { word: "Baile", hint: "Ritmo" },
        { word: "Torta", hint: "Capas" },
        { word: "Velas", hint: "Soplo" },
        { word: "Regalo", hint: "Envoltura" },
        { word: "Invitación", hint: "Confirmación" },
        { word: "Brindis", hint: "Cristal" },
        { word: "Champán", hint: "Corcho" },
        { word: "Cerveza", hint: "Malta" },
        { word: "Ron", hint: "Caribe" },
        { word: "Vodka", hint: "Destilado" },
        { word: "Whisky", hint: "Bourbon" },
        { word: "Mojito", hint: "Hierbabuena" },
        { word: "Karaoke", hint: "Letras" },
        { word: "DJ", hint: "Mezcla" },
        { word: "Pizza", hint: "Mozzarella" },
        { word: "Empanadas", hint: "Relleno" },
        { word: "Papas fritas", hint: "Aceite" },
        { word: "Helado", hint: "Cremoso" },
        { word: "Gelatina", hint: "Temblor" },
        { word: "Ponche", hint: "Tazón" },
        { word: "Gaseosa", hint: "Burbujas" },
        { word: "Hielo", hint: "Cubos" },
        { word: "Vasos", hint: "Desechable" },
        { word: "Platos", hint: "Porcelana" },
        { word: "Servilletas", hint: "Doblado" },
        { word: "Mantel", hint: "Tela" },
        { word: "Sillas", hint: "Apilables" },
        { word: "Mesa", hint: "Superficie" },
        { word: "Luces", hint: "Intermitente" },
        { word: "Guirnalda", hint: "Colgante" },
        { word: "Serpentina", hint: "Espiral" },
        { word: "Máscara", hint: "Ocultar" },
        { word: "Disfraz", hint: "Personaje" },
        { word: "Sombrero", hint: "Copa" },
        { word: "Guitarra", hint: "Trastes" },
        { word: "Micrófono", hint: "Amplificación" },
        { word: "Parlante", hint: "Woofer" },
        { word: "Foto", hint: "Instantánea" },
        { word: "Selfie", hint: "Brazo" },
        { word: "Video", hint: "Grabación" },
        { word: "Pista", hint: "Baile" },
        { word: "Anfitrión", hint: "Organizador" },
        { word: "Invitado", hint: "Lista" },
        { word: "Abrazo", hint: "Brazos" },
        { word: "Beso", hint: "Labios" },
        { word: "Risa", hint: "Carcajada" },
        { word: "Aplauso", hint: "Palmas" },
        { word: "Sorpresa", hint: "Ojos" },
        { word: "Payaso", hint: "Nariz" },
        { word: "Mago", hint: "Sombrero" },
        { word: "Piñata", hint: "Palo" },
        { word: "Caramelos", hint: "Envoltura" },
        { word: "Chocolate", hint: "Cacao" },
        { word: "Chicle", hint: "Masticar" },
        { word: "Palomitas", hint: "Explosión" },
        { word: "Cumpleaños", hint: "Edad" },
        { word: "Aniversario", hint: "Fecha" },
        { word: "Graduación", hint: "Birrete" },
        { word: "Boda", hint: "Anillos" },
        { word: "Bautizo", hint: "Padrinos" },
        { word: "Despedida", hint: "Soltera" },
        { word: "Festival", hint: "Escenario" },
        { word: "Carnaval", hint: "Comparsas" },
        { word: "Feria", hint: "Stands" },
        { word: "Pijamada", hint: "Almohadas" },
        { word: "Fogata", hint: "Leña" },
        { word: "Parrillada", hint: "Parrilla" },
        { word: "Picnic", hint: "Canasta" },
        { word: "Discoteca", hint: "Bola" },
        { word: "Bar", hint: "Barra" },
        { word: "Club", hint: "Membresía" },
        { word: "Terraza", hint: "Vista" },
        { word: "Playa", hint: "Arena" },
        { word: "Decoración", hint: "Adornos" },
        { word: "Flores", hint: "Pétalos" },
        { word: "Rosas", hint: "Espinas" },
        { word: "Banderines", hint: "Triángulos" },
        { word: "Burbujas", hint: "Jabón" },
        { word: "Hora loca", hint: "Máscaras" },
        { word: "Animador", hint: "Show" },
        { word: "Bartender", hint: "Coctelería" },
        { word: "Mesero", hint: "Bandeja" },
        { word: "Fotógrafo", hint: "Flash" },
        { word: "Playlist", hint: "Canciones" },
        { word: "Volumen", hint: "Amplificador" },
        { word: "Reggaeton", hint: "Perreo" },
        { word: "Salsa", hint: "Clave" },
        { word: "Merengue", hint: "Cadera" },
        { word: "Bachata", hint: "Romántico" },
        { word: "Cumbia", hint: "Colombiana" },
        { word: "Rock", hint: "Guitarra" },
        { word: "Pop", hint: "Pegajoso" },
        { word: "Fiesta", hint: "Celebración" },
        { word: "Diversión", hint: "Entretenimiento" },
        { word: "Alegría", hint: "Felicidad" }
    ],

    celebridades: [
        { word: "Shakira", hint: "Cadera" },
        { word: "Messi", hint: "Pulga" },
        { word: "Cristiano", hint: "Siete" },
        { word: "Neymar", hint: "Brasil" },
        { word: "Bad Bunny", hint: "Conejo" },
        { word: "Karol G", hint: "Bichota" },
        { word: "Maluma", hint: "Pretty" },
        { word: "J Balvin", hint: "Colores" },
        { word: "Daddy Yankee", hint: "Gasolina" },
        { word: "Ozuna", hint: "Negrito" },
        { word: "Peso Pluma", hint: "Plumas" },
        { word: "Bizarrap", hint: "Sessions" },
        { word: "Rosalía", hint: "Motomami" },
        { word: "Marc Anthony", hint: "Salsa" },
        { word: "Enrique Iglesias", hint: "Bailando" },
        { word: "Luis Fonsi", hint: "Despacito" },
        { word: "Ariana Grande", hint: "Thank" },
        { word: "Taylor Swift", hint: "Folklore" },
        { word: "Billie Eilish", hint: "Bad" },
        { word: "The Weeknd", hint: "Blinding" },
        { word: "Justin Bieber", hint: "Baby" },
        { word: "Beyoncé", hint: "Queen" },
        { word: "Rihanna", hint: "Umbrella" },
        { word: "Lady Gaga", hint: "Poker" },
        { word: "Katy Perry", hint: "Roar" },
        { word: "Madonna", hint: "Material" },
        { word: "Jennifer Lopez", hint: "Block" },
        { word: "Michael Jackson", hint: "King" },
        { word: "BTS", hint: "Dynamite" },
        { word: "Tom Cruise", hint: "Mission" },
        { word: "Brad Pitt", hint: "Fight" },
        { word: "Leonardo DiCaprio", hint: "Titanic" },
        { word: "Johnny Depp", hint: "Pirates" },
        { word: "Will Smith", hint: "Fresh" },
        { word: "Dwayne Johnson", hint: "Rock" },
        { word: "Robert Downey", hint: "Iron" },
        { word: "Chris Evans", hint: "Captain" },
        { word: "Scarlett Johansson", hint: "Black" },
        { word: "Emma Watson", hint: "Hermione" },
        { word: "Angelina Jolie", hint: "Lara" },
        { word: "Margot Robbie", hint: "Harley" },
        { word: "Zendaya", hint: "Spider" },
        { word: "Tom Holland", hint: "Spider" },
        { word: "Vin Diesel", hint: "Furious" },
        { word: "Elon Musk", hint: "Tesla" },
        { word: "Jeff Bezos", hint: "Amazon" },
        { word: "Bill Gates", hint: "Microsoft" },
        { word: "Mark Zuckerberg", hint: "Facebook" },
        { word: "Steve Jobs", hint: "Apple" },
        { word: "Ed Sheeran", hint: "Shape" },
        { word: "Bruno Mars", hint: "Uptown" },
        { word: "Drake", hint: "Hotline" },
        { word: "Eminem", hint: "Rap" },
        { word: "Kanye West", hint: "Yeezy" },
        { word: "Post Malone", hint: "Circles" },
        { word: "Ryan Reynolds", hint: "Deadpool" },
        { word: "Chris Hemsworth", hint: "Thor" },
        { word: "Jason Momoa", hint: "Aquaman" },
        { word: "Keanu Reeves", hint: "Matrix" },
        { word: "Morgan Freeman", hint: "Narrador" },
        { word: "Samuel L Jackson", hint: "Fury" },
        { word: "Ryan Gosling", hint: "Drive" },
        { word: "Christian Bale", hint: "Batman" },
        { word: "Hugh Jackman", hint: "Wolverine" },
        { word: "Anne Hathaway", hint: "Princess" },
        { word: "Sandra Bullock", hint: "Gravity" },
        { word: "Julia Roberts", hint: "Pretty" },
        { word: "Meryl Streep", hint: "Devil" },
        { word: "Charlize Theron", hint: "Mad" },
        { word: "Penélope Cruz", hint: "Española" },
        { word: "Salma Hayek", hint: "Mexicana" },
        { word: "Kate Winslet", hint: "Rose" },
        { word: "Daniel Radcliffe", hint: "Potter" },
        { word: "Lionel Messi", hint: "Argentina" },
        { word: "Cristiano Ronaldo", hint: "Portugal" },
        { word: "Neymar Jr", hint: "Brasil" },
        { word: "Kylian Mbappé", hint: "Francia" },
        { word: "Erling Haaland", hint: "Noruega" },
        { word: "Sergio Ramos", hint: "España" },
        { word: "Zlatan Ibrahimovic", hint: "Suecia" },
        { word: "Luis Suárez", hint: "Uruguay" },
        { word: "James Rodríguez", hint: "Colombia" },
        { word: "Alexis Sánchez", hint: "Chile" },
        { word: "Paolo Guerrero", hint: "Perú" },
        { word: "Jefferson Farfán", hint: "Foquita" },
        { word: "Claudio Pizarro", hint: "Bomber" },
        { word: "Gianluca Lapadula", hint: "Italia" },
        { word: "André Carrillo", hint: "Culebra" },
        { word: "Christian Cueva", hint: "Aladino" },
        { word: "Renato Tapia", hint: "Cabezón" },
        { word: "Pedro Gallese", hint: "Pulpo" },
        { word: "Adele", hint: "Hello" },
        { word: "Cardi B", hint: "Okurrr" },
        { word: "Harry Styles", hint: "Watermelon" },
        { word: "Dua Lipa", hint: "Levitating" },
        { word: "Miley Cyrus", hint: "Wrecking" },
        { word: "Selena Gomez", hint: "Rare" },
        { word: "Camila Cabello", hint: "Havana" },
        { word: "Nicki Minaj", hint: "Barbie" }
    ],

    navidad: [
        { word: "Santa Claus", hint: "Barba" },
        { word: "Papá Noel", hint: "Trineo" },
        { word: "Árbol", hint: "Pino" },
        { word: "Regalos", hint: "Papel" },
        { word: "Nieve", hint: "Blanca" },
        { word: "Estrella", hint: "Punta" },
        { word: "Corona", hint: "Puerta" },
        { word: "Velas", hint: "Mecha" },
        { word: "Campanas", hint: "Repique" },
        { word: "Villancicos", hint: "Coro" },
        { word: "Trineo", hint: "Madera" },
        { word: "Renos", hint: "Cuernos" },
        { word: "Calcetín", hint: "Chimenea" },
        { word: "Chimenea", hint: "Hollín" },
        { word: "Galletas", hint: "Leche" },
        { word: "Jengibre", hint: "Hombre" },
        { word: "Bastón", hint: "Rayado" },
        { word: "Luces", hint: "Series" },
        { word: "Adornos", hint: "Esferas" },
        { word: "Esferas", hint: "Vidrio" },
        { word: "Nacimiento", hint: "Pesebre" },
        { word: "Belén", hint: "Portal" },
        { word: "José", hint: "Carpintero" },
        { word: "María", hint: "Madre" },
        { word: "Jesús", hint: "Niño" },
        { word: "Ángel", hint: "Alas" },
        { word: "Pastor", hint: "Ovejas" },
        { word: "Reyes Magos", hint: "Tres" },
        { word: "Melchor", hint: "Rey" },
        { word: "Gaspar", hint: "Rey" },
        { word: "Baltazar", hint: "Rey" },
        { word: "Camello", hint: "Joroba" },
        { word: "Oro", hint: "Metal" },
        { word: "Incienso", hint: "Resina" },
        { word: "Pavo", hint: "Ave" },
        { word: "Jamón", hint: "Cerdo" },
        { word: "Lechón", hint: "Asado" },
        { word: "Tamales", hint: "Maíz" },
        { word: "Ponche", hint: "Caliente" },
        { word: "Champán", hint: "Burbujas" },
        { word: "Chocolate", hint: "Caliente" },
        { word: "Panetón", hint: "Italia" },
        { word: "Turrón", hint: "Almendra" },
        { word: "Nueces", hint: "Cáscara" },
        { word: "Uvas", hint: "Doce" },
        { word: "Medianoche", hint: "Doce" },
        { word: "Año Nuevo", hint: "Cuenta" },
        { word: "Aguinaldo", hint: "Bono" },
        { word: "Carta", hint: "Deseos" },
        { word: "Juguetes", hint: "Niños" },
        { word: "Muñeca", hint: "Brazos" },
        { word: "Carrito", hint: "Ruedas" },
        { word: "Pelota", hint: "Esférica" },
        { word: "Bicicleta", hint: "Pedales" },
        { word: "Videojuego", hint: "Consola" },
        { word: "Tablet", hint: "Pantalla" },
        { word: "Celular", hint: "Teléfono" },
        { word: "Ropa", hint: "Vestir" },
        { word: "Chompa", hint: "Lana" },
        { word: "Bufanda", hint: "Cuello" },
        { word: "Guantes", hint: "Dedos" },
        { word: "Gorro", hint: "Cabeza" },
        { word: "Botas", hint: "Altas" },
        { word: "Pijama", hint: "Dormir" },
        { word: "Perfume", hint: "Fragancia" },
        { word: "Reloj", hint: "Muñeca" },
        { word: "Collar", hint: "Cuello" },
        { word: "Pulsera", hint: "Muñeca" },
        { word: "Aretes", hint: "Orejas" },
        { word: "Anillo", hint: "Dedo" },
        { word: "Billetera", hint: "Dinero" },
        { word: "Mochila", hint: "Espalda" },
        { word: "Libro", hint: "Páginas" },
        { word: "Calendario", hint: "Fechas" },
        { word: "Tarjeta", hint: "Cartón" },
        { word: "Paquete", hint: "Caja" },
        { word: "Caja", hint: "Envoltorio" },
        { word: "Moño", hint: "Lazo" },
        { word: "Cinta", hint: "Decorativa" },
        { word: "Papel", hint: "Regalo" },
        { word: "Tijeras", hint: "Cortar" },
        { word: "Familia", hint: "Reunión" },
        { word: "Abuelos", hint: "Mayores" },
        { word: "Padres", hint: "Mamá" },
        { word: "Hijos", hint: "Niños" },
        { word: "Hermanos", hint: "Familia" },
        { word: "Primos", hint: "Parientes" },
        { word: "Tíos", hint: "Familia" },
        { word: "Cena", hint: "Mesa" },
        { word: "Abrazo", hint: "Brazos" },
        { word: "Beso", hint: "Labios" },
        { word: "Amor", hint: "Sentimiento" },
        { word: "Paz", hint: "Paloma" },
        { word: "Alegría", hint: "Felicidad" },
        { word: "Esperanza", hint: "Verde" },
        { word: "Fe", hint: "Creencia" },
        { word: "Noche Buena", hint: "Víspera" },
        { word: "Misa", hint: "Iglesia" }
    ],

    comida: [
        { word: "Pizza", hint: "Horno" },
        { word: "Hamburguesa", hint: "Pan" },
        { word: "Tacos", hint: "Tortilla" },
        { word: "Sushi", hint: "Arroz" },
        { word: "Pasta", hint: "Trigo" },
        { word: "Arroz", hint: "Grano" },
        { word: "Pollo", hint: "Ave" },
        { word: "Carne", hint: "Res" },
        { word: "Pescado", hint: "Escamas" },
        { word: "Camarones", hint: "Cola" },
        { word: "Ensalada", hint: "Lechuga" },
        { word: "Sopa", hint: "Caldo" },
        { word: "Pan", hint: "Levadura" },
        { word: "Empanadas", hint: "Doblez" },
        { word: "Tamales", hint: "Hoja" },
        { word: "Hot dog", hint: "Salchicha" },
        { word: "Sandwich", hint: "Rebanadas" },
        { word: "Queso", hint: "Leche" },
        { word: "Mantequilla", hint: "Amarilla" },
        { word: "Yogurt", hint: "Fermentado" },
        { word: "Leche", hint: "Vaca" },
        { word: "Huevo", hint: "Gallina" },
        { word: "Palta", hint: "Verde" },
        { word: "Mayonesa", hint: "Emulsión" },
        { word: "Ketchup", hint: "Tomate" },
        { word: "Mostaza", hint: "Amarilla" },
        { word: "Ajo", hint: "Diente" },
        { word: "Cebolla", hint: "Capas" },
        { word: "Tomate", hint: "Rojo" },
        { word: "Ají", hint: "Picante" },
        { word: "Papa", hint: "Tubérculo" },
        { word: "Camote", hint: "Dulce" },
        { word: "Yuca", hint: "Mandioca" },
        { word: "Zanahoria", hint: "Naranja" },
        { word: "Lechuga", hint: "Hojas" },
        { word: "Brócoli", hint: "Arbolito" },
        { word: "Manzana", hint: "Eva" },
        { word: "Plátano", hint: "Potasio" },
        { word: "Naranja", hint: "Cítrico" },
        { word: "Limón", hint: "Ácido" },
        { word: "Uva", hint: "Racimo" },
        { word: "Fresa", hint: "Semillas" },
        { word: "Durazno", hint: "Peludo" },
        { word: "Mango", hint: "Tropical" },
        { word: "Piña", hint: "Espinas" },
        { word: "Papaya", hint: "Naranja" },
        { word: "Sandía", hint: "Semillas" },
        { word: "Melón", hint: "Dulce" },
        { word: "Coco", hint: "Peludo" },
        { word: "Maracuyá", hint: "Pasión" },
        { word: "Lúcuma", hint: "Helado" },
        { word: "Chirimoya", hint: "Escamas" },
        { word: "Chocolate", hint: "Cacao" },
        { word: "Café", hint: "Grano" },
        { word: "Té", hint: "Hojas" },
        { word: "Gaseosa", hint: "Gas" },
        { word: "Jugo", hint: "Exprimido" },
        { word: "Agua", hint: "Hidratación" },
        { word: "Cerveza", hint: "Lúpulo" },
        { word: "Vino", hint: "Uva" },
        { word: "Pisco", hint: "Perú" },
        { word: "Chicha", hint: "Morada" },
        { word: "Inca Kola", hint: "Amarilla" },
        { word: "Limonada", hint: "Cítrico" },
        { word: "Helado", hint: "Congelado" },
        { word: "Paleta", hint: "Palo" },
        { word: "Flan", hint: "Caramelo" },
        { word: "Gelatina", hint: "Grenetina" },
        { word: "Torta", hint: "Betún" },
        { word: "Galletas", hint: "Crujientes" },
        { word: "Donas", hint: "Agujero" },
        { word: "Churros", hint: "Azúcar" },
        { word: "Picarones", hint: "Miel" },
        { word: "Alfajor", hint: "Manjar" },
        { word: "Suspiro", hint: "Limeño" },
        { word: "Mazamorra", hint: "Morada" },
        { word: "Arroz con leche", hint: "Canela" },
        { word: "Ceviche", hint: "Limón" },
        { word: "Lomo saltado", hint: "Wok" },
        { word: "Ají de gallina", hint: "Amarillo" },
        { word: "Causa", hint: "Papa" },
        { word: "Anticuchos", hint: "Corazón" },
        { word: "Pachamanca", hint: "Tierra" },
        { word: "Tacu tacu", hint: "Frito" },
        { word: "Carapulcra", hint: "Papa" },
        { word: "Seco", hint: "Cilantro" },
        { word: "Arroz chaufa", hint: "Chino" },
        { word: "Tallarín", hint: "Saltado" },
        { word: "Pollo a la brasa", hint: "Carbón" },
        { word: "Salchipapa", hint: "Papas" },
        { word: "Butifarra", hint: "Pan" },
        { word: "Chicharrón", hint: "Cerdo" },
        { word: "Rocoto relleno", hint: "Picante" },
        { word: "Jugo de papaya", hint: "Naranja" },
        { word: "Té helado", hint: "Frío" },
        { word: "Cappuccino", hint: "Espuma" },
        { word: "Frappé", hint: "Batido" }
    ],

    hollywood: [
        { word: "Titanic", hint: "Barco" },
        { word: "Avatar", hint: "Azul" },
        { word: "Avengers", hint: "Equipo" },
        { word: "Iron Man", hint: "Armadura" },
        { word: "Spider Man", hint: "Telaraña" },
        { word: "Batman", hint: "Murciélago" },
        { word: "Superman", hint: "Capa" },
        { word: "Wonder Woman", hint: "Lazo" },
        { word: "Harry Potter", hint: "Varita" },
        { word: "Star Wars", hint: "Sable" },
        { word: "Matrix", hint: "Píldora" },
        { word: "Terminator", hint: "Robot" },
        { word: "Jurassic Park", hint: "Dinosaurios" },
        { word: "Tiburón", hint: "Aleta" },
        { word: "ET", hint: "Extraterrestre" },
        { word: "Indiana Jones", hint: "Látigo" },
        { word: "Rocky", hint: "Boxeo" },
        { word: "Rambo", hint: "Cinta" },
        { word: "Forrest Gump", hint: "Pluma" },
        { word: "Gladiador", hint: "Coliseo" },
        { word: "Troya", hint: "Caballo" },
        { word: "300", hint: "Espartanos" },
        { word: "Shrek", hint: "Ogro" },
        { word: "Toy Story", hint: "Juguetes" },
        { word: "Buscando a Nemo", hint: "Pez" },
        { word: "Frozen", hint: "Hielo" },
        { word: "Moana", hint: "Océano" },
        { word: "Coco", hint: "Guitarra" },
        { word: "Up", hint: "Globos" },
        { word: "Wall E", hint: "Robot" },
        { word: "Monsters Inc", hint: "Puerta" },
        { word: "Cars", hint: "Rayo" },
        { word: "Ratatouille", hint: "Rata" },
        { word: "Intensamente", hint: "Emociones" },
        { word: "El Rey León", hint: "Simba" },
        { word: "Aladino", hint: "Lámpara" },
        { word: "La Bella y la Bestia", hint: "Rosa" },
        { word: "Mulan", hint: "Dragón" },
        { word: "Pocahontas", hint: "Viento" },
        { word: "Hércules", hint: "Zeus" },
        { word: "Tarzán", hint: "Liana" },
        { word: "Dumbo", hint: "Orejas" },
        { word: "Bambi", hint: "Cervatillo" },
        { word: "Pinocho", hint: "Nariz" },
        { word: "Cenicienta", hint: "Zapatilla" },
        { word: "Blanca Nieves", hint: "Manzana" },
        { word: "La Sirenita", hint: "Voz" },
        { word: "Enredados", hint: "Cabello" },
        { word: "Zootopia", hint: "Animales" },
        { word: "Encanto", hint: "Casita" },
        { word: "Los Increíbles", hint: "Familia" },
        { word: "Mi villano favorito", hint: "Minions" },
        { word: "Kung Fu Panda", hint: "Oso" },
        { word: "Madagascar", hint: "Cebra" },
        { word: "La Era de Hielo", hint: "Bellota" },
        { word: "El Gato con Botas", hint: "Gato" },
        { word: "Minions", hint: "Amarillo" },
        { word: "Snoopy", hint: "Beagle" },
        { word: "Garfield", hint: "Lasaña" },
        { word: "Tom y Jerry", hint: "Persecución" },
        { word: "Mickey Mouse", hint: "Orejas" },
        { word: "Pato Donald", hint: "Pato" },
        { word: "Winnie Pooh", hint: "Miel" },
        { word: "Dumbledore", hint: "Director" },
        { word: "Voldemort", hint: "Calvo" },
        { word: "Hermione", hint: "Inteligente" },
        { word: "Ron", hint: "Pelirrojo" },
        { word: "Hogwarts", hint: "Castillo" },
        { word: "Luke Skywalker", hint: "Granjero" },
        { word: "Darth Vader", hint: "Respiración" },
        { word: "Yoda", hint: "Verde" },
        { word: "Chewbacca", hint: "Peludo" },
        { word: "Han Solo", hint: "Contrabandista" },
        { word: "Leia", hint: "Princesa" },
        { word: "R2D2", hint: "Beep" },
        { word: "Neo", hint: "Elegido" },
        { word: "Woody", hint: "Sheriff" },
        { word: "Buzz Lightyear", hint: "Espacio" },
        { word: "Elsa", hint: "Nieve" },
        { word: "Anna", hint: "Hermana" },
        { word: "Olaf", hint: "Muñeco" },
        { word: "Simba", hint: "Cachorro" },
        { word: "Mufasa", hint: "Padre" },
        { word: "Scar", hint: "Cicatriz" },
        { word: "Nala", hint: "Leona" },
        { word: "Genio", hint: "Tres" },
        { word: "Jasmín", hint: "Tigre" },
        { word: "Fast and Furious", hint: "Velocidad" },
        { word: "Misión Imposible", hint: "Espía" },
        { word: "James Bond", hint: "007" },
        { word: "Piratas del Caribe", hint: "Jack" },
        { word: "Señor de los Anillos", hint: "Anillo" },
        { word: "El Padrino", hint: "Mafia" },
        { word: "Scarface", hint: "Cicatriz" },
        { word: "Casino", hint: "Apuesta" },
        { word: "Volver al Futuro", hint: "DeLorean" },
        { word: "Ghostbusters", hint: "Fantasmas" }
    ],

    marcas: [
        { word: "Nike", hint: "Swoosh" },
        { word: "Adidas", hint: "Tres" },
        { word: "Puma", hint: "Felino" },
        { word: "Apple", hint: "Manzana" },
        { word: "Samsung", hint: "Galaxy" },
        { word: "Huawei", hint: "China" },
        { word: "Sony", hint: "PlayStation" },
        { word: "LG", hint: "Sonrisa" },
        { word: "Microsoft", hint: "Ventanas" },
        { word: "Google", hint: "G" },
        { word: "Facebook", hint: "F" },
        { word: "Instagram", hint: "Cámara" },
        { word: "Twitter", hint: "Pájaro" },
        { word: "TikTok", hint: "Musical" },
        { word: "YouTube", hint: "Play" },
        { word: "WhatsApp", hint: "Bocadillo" },
        { word: "Amazon", hint: "Sonrisa" },
        { word: "Netflix", hint: "N" },
        { word: "Disney", hint: "Ratón" },
        { word: "Spotify", hint: "Verde" },
        { word: "Uber", hint: "U" },
        { word: "Visa", hint: "Azul" },
        { word: "Mastercard", hint: "Círculos" },
        { word: "Coca Cola", hint: "Roja" },
        { word: "Pepsi", hint: "Esfera" },
        { word: "Sprite", hint: "Verde" },
        { word: "Fanta", hint: "Naranja" },
        { word: "Inca Kola", hint: "Amarilla" },
        { word: "Red Bull", hint: "Toros" },
        { word: "Gatorade", hint: "Rayo" },
        { word: "Nestlé", hint: "Nido" },
        { word: "Gloria", hint: "Leche" },
        { word: "Laive", hint: "Yogurt" },
        { word: "Donofrio", hint: "Helado" },
        { word: "Sublime", hint: "Chocolate" },
        { word: "Oreo", hint: "Galleta" },
        { word: "Pringles", hint: "Bigote" },
        { word: "Doritos", hint: "Triángulo" },
        { word: "Lay's", hint: "Papa" },
        { word: "McDonald's", hint: "M" },
        { word: "Burger King", hint: "Rey" },
        { word: "KFC", hint: "Coronel" },
        { word: "Starbucks", hint: "Sirena" },
        { word: "Bembos", hint: "Perú" },
        { word: "Pardos", hint: "Pollo" },
        { word: "Toyota", hint: "T" },
        { word: "Honda", hint: "H" },
        { word: "Nissan", hint: "Círculo" },
        { word: "Hyundai", hint: "H" },
        { word: "Ford", hint: "Óvalo" },
        { word: "Chevrolet", hint: "Cruz" },
        { word: "BMW", hint: "Hélice" },
        { word: "Mercedes", hint: "Estrella" },
        { word: "Audi", hint: "Aros" },
        { word: "Volkswagen", hint: "VW" },
        { word: "Ferrari", hint: "Caballo" },
        { word: "Lamborghini", hint: "Toro" },
        { word: "Zara", hint: "Z" },
        { word: "H&M", hint: "HM" },
        { word: "Gucci", hint: "GG" },
        { word: "Louis Vuitton", hint: "LV" },
        { word: "Prada", hint: "Triángulo" },
        { word: "Chanel", hint: "CC" },
        { word: "Rolex", hint: "Corona" },
        { word: "Casio", hint: "Digital" },
        { word: "Ikea", hint: "Azul" },
        { word: "Walmart", hint: "W" },
        { word: "Plaza Vea", hint: "Plaza" },
        { word: "Tottus", hint: "Supermercado" },
        { word: "Metro", hint: "Wong" },
        { word: "Sodimac", hint: "Construcción" },
        { word: "Ripley", hint: "Tienda" },
        { word: "Saga Falabella", hint: "Tienda" },
        { word: "Oechsle", hint: "Tienda" },
        { word: "Real Plaza", hint: "Mall" },
        { word: "Jockey Plaza", hint: "Centro" },
        { word: "Larcomar", hint: "Vista" },
        { word: "Panasonic", hint: "Ideas" },
        { word: "Philips", hint: "Escudo" },
        { word: "Gillette", hint: "Navaja" },
        { word: "Colgate", hint: "Rojo" },
        { word: "Nivea", hint: "Azul" },
        { word: "Dove", hint: "Paloma" },
        { word: "Pantene", hint: "P" },
        { word: "Head & Shoulders", hint: "Caspa" },
        { word: "Converse", hint: "Estrella" },
        { word: "Reebok", hint: "Deporte" },
        { word: "Under Armour", hint: "UA" },
        { word: "New Balance", hint: "NB" },
        { word: "Vans", hint: "Skate" },
        { word: "Fila", hint: "Italia" },
        { word: "Lacoste", hint: "Cocodrilo" },
        { word: "Tommy Hilfiger", hint: "Bandera" },
        { word: "Ralph Lauren", hint: "Polo" },
        { word: "Calvin Klein", hint: "CK" },
        { word: "Levi's", hint: "Jeans" },
        { word: "Diesel", hint: "Denim" }
    ],

    lugares: [
        { word: "París", hint: "Torre" },
        { word: "Londres", hint: "Reloj" },
        { word: "Roma", hint: "Coliseo" },
        { word: "Tokio", hint: "Fuji" },
        { word: "Nueva York", hint: "Manzana" },
        { word: "Los Ángeles", hint: "Hollywood" },
        { word: "Miami", hint: "Playa" },
        { word: "Las Vegas", hint: "Casino" },
        { word: "San Francisco", hint: "Puente" },
        { word: "Washington", hint: "Capital" },
        { word: "México", hint: "Azteca" },
        { word: "Cancún", hint: "Turquesa" },
        { word: "Buenos Aires", hint: "Tango" },
        { word: "Río de Janeiro", hint: "Cristo" },
        { word: "Lima", hint: "Pisco" },
        { word: "Cusco", hint: "Ombligo" },
        { word: "Machu Picchu", hint: "Ruinas" },
        { word: "Arequipa", hint: "Blanca" },
        { word: "Trujillo", hint: "Primavera" },
        { word: "Chiclayo", hint: "Amistad" },
        { word: "Piura", hint: "Calor" },
        { word: "Iquitos", hint: "Selva" },
        { word: "Puno", hint: "Titicaca" },
        { word: "Nazca", hint: "Líneas" },
        { word: "Paracas", hint: "Reserva" },
        { word: "Huacachina", hint: "Oasis" },
        { word: "Máncora", hint: "Surf" },
        { word: "Ayacucho", hint: "Retablos" },
        { word: "Huaraz", hint: "Montañas" },
        { word: "Tarapoto", hint: "Palmeras" },
        { word: "Santiago", hint: "Andes" },
        { word: "Bogotá", hint: "Esmeraldas" },
        { word: "Madrid", hint: "Oso" },
        { word: "Barcelona", hint: "Sagrada" },
        { word: "Berlín", hint: "Muro" },
        { word: "Ámsterdam", hint: "Canales" },
        { word: "Viena", hint: "Vals" },
        { word: "Praga", hint: "Puente" },
        { word: "Milán", hint: "Moda" },
        { word: "Venecia", hint: "Góndolas" },
        { word: "Atenas", hint: "Partenón" },
        { word: "Estambul", hint: "Bósforo" },
        { word: "El Cairo", hint: "Pirámides" },
        { word: "Marrakech", hint: "Medina" },
        { word: "Dubái", hint: "Rascacielos" },
        { word: "Bangkok", hint: "Templos" },
        { word: "Pekín", hint: "Forbidden" },
        { word: "Shanghái", hint: "Bund" },
        { word: "Hong Kong", hint: "Victoria" },
        { word: "Sídney", hint: "Ópera" },
        { word: "Toronto", hint: "Canadá" },
        { word: "Vancouver", hint: "Costa" },
        { word: "Chicago", hint: "Viento" },
        { word: "Boston", hint: "Té" },
        { word: "Seattle", hint: "Aguja" },
        { word: "Orlando", hint: "Parques" },
        { word: "Hawái", hint: "Volcán" },
        { word: "Alaska", hint: "Hielo" },
        { word: "Amazonas", hint: "Selva" },
        { word: "Patagonia", hint: "Glaciares" },
        { word: "Galápagos", hint: "Tortugas" },
        { word: "Cartagena", hint: "Amurallada" },
        { word: "Medellín", hint: "Flores" },
        { word: "Quito", hint: "Mitad" },
        { word: "Caracas", hint: "Ávila" },
        { word: "La Paz", hint: "Altura" },
        { word: "Montevideo", hint: "Uruguay" },
        { word: "Asunción", hint: "Paraguay" },
        { word: "São Paulo", hint: "Industrial" },
        { word: "Salvador", hint: "Bahía" },
        { word: "Brasilia", hint: "Capital" },
        { word: "Fortaleza", hint: "Playa" },
        { word: "Copacabana", hint: "Arena" },
        { word: "Iguazú", hint: "Cataratas" },
        { word: "Aconcagua", hint: "Montaña" },
        { word: "Lago Titicaca", hint: "Flotantes" },
        { word: "Desierto Atacama", hint: "Seco" },
        { word: "Colca", hint: "Cañón" },
        { word: "Chan Chan", hint: "Barro" },
        { word: "Caral", hint: "Antigua" },
        { word: "Kuelap", hint: "Fortaleza" },
        { word: "Chavín", hint: "Cultura" },
        { word: "Sipán", hint: "Señor" },
        { word: "Choquequirao", hint: "Hermana" },
        { word: "Sacsayhuamán", hint: "Piedras" },
        { word: "Ollantaytambo", hint: "Valle" },
        { word: "Pisac", hint: "Mercado" },
        { word: "Miraflores", hint: "Malecón" },
        { word: "Barranco", hint: "Puente" },
        { word: "San Isidro", hint: "Golf" },
        { word: "Callao", hint: "Puerto" },
        { word: "Surco", hint: "Lima" },
        { word: "La Molina", hint: "Universidad" },
        { word: "Ate", hint: "Este" },
        { word: "Comas", hint: "Norte" },
        { word: "San Juan de Lurigancho", hint: "Población" }
    ],

    animales: [
        { word: "Perro", hint: "Ladrido" },
        { word: "Gato", hint: "Maullido" },
        { word: "Ratón", hint: "Roedor" },
        { word: "Elefante", hint: "Trompa" },
        { word: "León", hint: "Melena" },
        { word: "Tigre", hint: "Rayas" },
        { word: "Oso", hint: "Miel" },
        { word: "Panda", hint: "Bambú" },
        { word: "Canguro", hint: "Marsupio" },
        { word: "Jirafa", hint: "Cuello" },
        { word: "Cebra", hint: "Rayas" },
        { word: "Hipopótamo", hint: "Agua" },
        { word: "Rinoceronte", hint: "Cuerno" },
        { word: "Camello", hint: "Joroba" },
        { word: "Llama", hint: "Escupir" },
        { word: "Alpaca", hint: "Lana" },
        { word: "Vicuña", hint: "Andina" },
        { word: "Mono", hint: "Plátano" },
        { word: "Gorila", hint: "Pecho" },
        { word: "Lobo", hint: "Aullido" },
        { word: "Zorro", hint: "Cola" },
        { word: "Conejo", hint: "Orejas" },
        { word: "Cuy", hint: "Chillido" },
        { word: "Caballo", hint: "Relincho" },
        { word: "Burro", hint: "Rebuzno" },
        { word: "Vaca", hint: "Mugido" },
        { word: "Toro", hint: "Cuernos" },
        { word: "Cerdo", hint: "Gruñido" },
        { word: "Oveja", hint: "Balido" },
        { word: "Cabra", hint: "Barbilla" },
        { word: "Gallina", hint: "Cacareo" },
        { word: "Gallo", hint: "Cresta" },
        { word: "Pato", hint: "Cuac" },
        { word: "Pavo", hint: "Gluglú" },
        { word: "Paloma", hint: "Zureo" },
        { word: "Loro", hint: "Habla" },
        { word: "Águila", hint: "Garras" },
        { word: "Cóndor", hint: "Andino" },
        { word: "Búho", hint: "Nocturno" },
        { word: "Gaviota", hint: "Costera" },
        { word: "Pelícano", hint: "Bolsa" },
        { word: "Flamenco", hint: "Rosa" },
        { word: "Pingüino", hint: "Frac" },
        { word: "Colibrí", hint: "Suspensión" },
        { word: "Golondrina", hint: "Migración" },
        { word: "Gorrión", hint: "Común" },
        { word: "Cocodrilo", hint: "Lagarto" },
        { word: "Tortuga", hint: "Caparazón" },
        { word: "Serpiente", hint: "Reptar" },
        { word: "Iguana", hint: "Cresta" },
        { word: "Rana", hint: "Salto" },
        { word: "Sapo", hint: "Verruga" },
        { word: "Tiburón", hint: "Aleta" },
        { word: "Ballena", hint: "Gigante" },
        { word: "Delfín", hint: "Silbido" },
        { word: "Lobo marino", hint: "Ladrido" },
        { word: "Nutria", hint: "Juguetona" },
        { word: "Pez", hint: "Escamas" },
        { word: "Anchoveta", hint: "Pequeña" },
        { word: "Atún", hint: "Lata" },
        { word: "Pulpo", hint: "Ocho" },
        { word: "Calamar", hint: "Tinta" },
        { word: "Medusa", hint: "Tentáculos" },
        { word: "Cangrejo", hint: "Pinzas" },
        { word: "Langostino", hint: "Grande" },
        { word: "Caracol", hint: "Espiral" },
        { word: "Hormiga", hint: "Fila" },
        { word: "Abeja", hint: "Panal" },
        { word: "Avispa", hint: "Aguijón" },
        { word: "Mosca", hint: "Zumbido" },
        { word: "Mosquito", hint: "Picadura" },
        { word: "Mariposa", hint: "Alas" },
        { word: "Libélula", hint: "Cuatro" },
        { word: "Escarabajo", hint: "Caparazón" },
        { word: "Mariquita", hint: "Puntos" },
        { word: "Grillo", hint: "Chirriado" },
        { word: "Saltamontes", hint: "Salto" },
        { word: "Araña", hint: "Ocho" },
        { word: "Tarántula", hint: "Peluda" },
        { word: "Escorpión", hint: "Aguijón" },
        { word: "Loro", hint: "Colorido" },
        { word: "Guacamayo", hint: "Grande" },
        { word: "Tucán", hint: "Pico" },
        { word: "Pájaro", hint: "Volar" },
        { word: "Cisne", hint: "Blanco" },
        { word: "Pato", hint: "Lago" },
        { word: "Ganso", hint: "Honk" },
        { word: "Avestruz", hint: "Veloz" },
        { word: "Murciélago", hint: "Nocturno" },
        { word: "Ardilla", hint: "Nueces" },
        { word: "Castor", hint: "Dientes" },
        { word: "Mapache", hint: "Antifaz" },
        { word: "Koala", hint: "Eucalipto" },
        { word: "Orca", hint: "Blanco" },
        { word: "Foca", hint: "Bigotes" },
        { word: "Morsa", hint: "Colmillos" }
    ],

    deportes: [
        { word: "Fútbol", hint: "Gol" },
        { word: "Vóley", hint: "Red" },
        { word: "Básquet", hint: "Canasta" },
        { word: "Tenis", hint: "Raqueta" },
        { word: "Natación", hint: "Piscina" },
        { word: "Atletismo", hint: "Pista" },
        { word: "Boxeo", hint: "Ring" },
        { word: "Karate", hint: "Kata" },
        { word: "Judo", hint: "Tatami" },
        { word: "Taekwondo", hint: "Patada" },
        { word: "Ciclismo", hint: "Pedal" },
        { word: "Surf", hint: "Tabla" },
        { word: "Skateboard", hint: "Patineta" },
        { word: "Gimnasia", hint: "Anillas" },
        { word: "Escalada", hint: "Pared" },
        { word: "Maratón", hint: "42" },
        { word: "Golf", hint: "Hoyo" },
        { word: "Rugby", hint: "Oval" },
        { word: "Béisbol", hint: "Base" },
        { word: "Pelota", hint: "Redonda" },
        { word: "Arco", hint: "Portería" },
        { word: "Gol", hint: "Anotación" },
        { word: "Penalti", hint: "Penal" },
        { word: "Córner", hint: "Esquina" },
        { word: "Árbitro", hint: "Silbato" },
        { word: "Tarjeta", hint: "Roja" },
        { word: "Offside", hint: "Fuera" },
        { word: "Pelotazo", hint: "Golpe" },
        { word: "Cabezazo", hint: "Cabeza" },
        { word: "Chilena", hint: "Bicicleta" },
        { word: "Tiro libre", hint: "Falta" },
        { word: "Portero", hint: "Guantes" },
        { word: "Defensa", hint: "Atrás" },
        { word: "Mediocampista", hint: "Centro" },
        { word: "Delantero", hint: "Adelante" },
        { word: "Capitán", hint: "Brazalete" },
        { word: "Hincha", hint: "Aficionado" },
        { word: "Barra", hint: "Tribuna" },
        { word: "Estadio", hint: "Cancha" },
        { word: "Mundial", hint: "Copa" },
        { word: "Champions", hint: "Europa" },
        { word: "Libertadores", hint: "América" },
        { word: "Clásico", hint: "Rival" },
        { word: "Campeonato", hint: "Torneo" },
        { word: "Descenso", hint: "Bajar" },
        { word: "Ascenso", hint: "Subir" },
        { word: "Tabla", hint: "Posiciones" },
        { word: "Puntaje", hint: "Puntos" },
        { word: "Empate", hint: "Igualdad" },
        { word: "Victoria", hint: "Ganar" },
        { word: "Derrota", hint: "Perder" },
        { word: "Entrenador", hint: "Técnico" },
        { word: "Jugador", hint: "Deportista" },
        { word: "Equipo", hint: "Grupo" },
        { word: "Uniforme", hint: "Camiseta" },
        { word: "Botines", hint: "Zapatos" },
        { word: "Cancha", hint: "Campo" },
        { word: "Línea", hint: "Límite" },
        { word: "Centro", hint: "Círculo" },
        { word: "Esquina", hint: "Ángulo" },
        { word: "Banderín", hint: "Esquina" },
        { word: "Silbato", hint: "Pito" },
        { word: "Medalla", hint: "Oro" },
        { word: "Trofeo", hint: "Copa" },
        { word: "Podio", hint: "Tres" },
        { word: "Récord", hint: "Marca" },
        { word: "Olimpiadas", hint: "Anillos" },
        { word: "Juegos", hint: "Deportivos" },
        { word: "Competencia", hint: "Rival" },
        { word: "Partido", hint: "Encuentro" },
        { word: "Ronda", hint: "Fase" },
        { word: "Final", hint: "Última" },
        { word: "Semifinal", hint: "Penúltima" },
        { word: "Clasificación", hint: "Pase" },
        { word: "Eliminación", hint: "Fuera" },
        { word: "Calentamiento", hint: "Previo" },
        { word: "Estiramiento", hint: "Músculos" },
        { word: "Lesión", hint: "Daño" },
        { word: "Recuperación", hint: "Sanar" },
        { word: "Fisioterapia", hint: "Terapia" },
        { word: "Hidratación", hint: "Agua" },
        { word: "Nutrición", hint: "Alimentación" },
        { word: "Entrenamiento", hint: "Práctica" },
        { word: "Táctica", hint: "Estrategia" },
        { word: "Técnica", hint: "Habilidad" },
        { word: "Velocidad", hint: "Rapidez" },
        { word: "Resistencia", hint: "Aguante" },
        { word: "Fuerza", hint: "Potencia" },
        { word: "Agilidad", hint: "Destreza" },
        { word: "Coordinación", hint: "Sincronía" },
        { word: "Reflejos", hint: "Reacción" },
        { word: "Pase", hint: "Envío" },
        { word: "Remate", hint: "Disparo" },
        { word: "Dribbling", hint: "Gambeta" },
        { word: "Intercepción", hint: "Corte" }
    ],

    picante: [
        { word: "Beso", hint: "Labios" },
        { word: "Abrazo", hint: "Brazos" },
        { word: "Caricia", hint: "Toque" },
        { word: "Pasión", hint: "Intenso" },
        { word: "Deseo", hint: "Anhelo" },
        { word: "Tentación", hint: "Provocación" },
        { word: "Seducción", hint: "Conquista" },
        { word: "Coqueteo", hint: "Insinuación" },
        { word: "Ligue", hint: "Encuentro" },
        { word: "Aventura", hint: "Pasajera" },
        { word: "Romance", hint: "Amor" },
        { word: "Enamoramiento", hint: "Flechazo" },
        { word: "Atracción", hint: "Magnetismo" },
        { word: "Química", hint: "Conexión" },
        { word: "Sensual", hint: "Provocativo" },
        { word: "Sexy", hint: "Atractivo" },
        { word: "Provocativo", hint: "Incitante" },
        { word: "Seductor", hint: "Encantador" },
        { word: "Irresistible", hint: "Magnético" },
        { word: "Atrevido", hint: "Osado" },
        { word: "Ardiente", hint: "Fogoso" },
        { word: "Travieso", hint: "Pícaro" },
        { word: "Juguetón", hint: "Divertido" },
        { word: "Misterioso", hint: "Enigmático" },
        { word: "Romántico", hint: "Amor" },
        { word: "Apasionado", hint: "Intenso" },
        { word: "Cariñoso", hint: "Tierno" },
        { word: "Delicado", hint: "Suave" },
        { word: "Íntimo", hint: "Privado" },
        { word: "Especial", hint: "Único" },
        { word: "Perfume", hint: "Aroma" },
        { word: "Vela", hint: "Cera" },
        { word: "Rosa", hint: "Flor" },
        { word: "Chocolate", hint: "Derretido" },
        { word: "Fresa", hint: "Fruta" },
        { word: "Champán", hint: "Celebración" },
        { word: "Copa", hint: "Vino" },
        { word: "Música", hint: "Melodía" },
        { word: "Baile", hint: "Movimiento" },
        { word: "Luna", hint: "Noche" },
        { word: "Estrellas", hint: "Cielo" },
        { word: "Playa", hint: "Arena" },
        { word: "Atardecer", hint: "Sol" },
        { word: "Mirada", hint: "Ojos" },
        { word: "Sonrisa", hint: "Labios" },
        { word: "Suspiro", hint: "Aire" },
        { word: "Corazón", hint: "Latido" },
        { word: "Mariposas", hint: "Estómago" },
        { word: "Piel", hint: "Suave" },
        { word: "Cabello", hint: "Sedoso" },
        { word: "Cuello", hint: "Delicado" },
        { word: "Manos", hint: "Entre" },
        { word: "Dedos", hint: "Entrelazados" },
        { word: "Mejillas", hint: "Sonrojadas" },
        { word: "Secreto", hint: "Oculto" },
        { word: "Sorpresa", hint: "Inesperado" },
        { word: "Regalo", hint: "Detalle" },
        { word: "Carta", hint: "Mensaje" },
        { word: "Poema", hint: "Versos" },
        { word: "Canción", hint: "Dedicada" },
        { word: "Serenata", hint: "Ventana" },
        { word: "Flores", hint: "Ramo" },
        { word: "Cita", hint: "Encuentro" },
        { word: "Paseo", hint: "Juntos" },
        { word: "Cena", hint: "Romántica" },
        { word: "Película", hint: "Juntos" },
        { word: "Parque", hint: "Banco" },
        { word: "Picnic", hint: "Manta" },
        { word: "Hotel", hint: "Suite" },
        { word: "Habitación", hint: "Privada" },
        { word: "Sábanas", hint: "Suaves" },
        { word: "Almohada", hint: "Cómoda" },
        { word: "Cobija", hint: "Calientita" },
        { word: "Ducha", hint: "Vapor" },
        { word: "Jacuzzi", hint: "Burbujas" },
        { word: "Masaje", hint: "Relajante" },
        { word: "Aceite", hint: "Aromático" },
        { word: "Crema", hint: "Hidratante" },
        { word: "Espejo", hint: "Reflejo" },
        { word: "Vestido", hint: "Elegante" },
        { word: "Tacones", hint: "Altos" },
        { word: "Corbata", hint: "Nudo" },
        { word: "Traje", hint: "Formal" },
        { word: "Lencería", hint: "Delicada" },
        { word: "Pijama", hint: "Seda" },
        { word: "Bata", hint: "Suave" },
        { word: "Toalla", hint: "Esponjosa" },
        { word: "Pantuflas", hint: "Cómodas" },
        { word: "Anillo", hint: "Compromiso" },
        { word: "Brazalete", hint: "Muñeca" },
        { word: "Pendientes", hint: "Orejas" },
        { word: "Collar", hint: "Cuello" },
        { word: "Reloj", hint: "Tiempo" },
        { word: "Pulsera", hint: "Brazalete" },
        { word: "Broche", hint: "Cierre" }
    ]
};

// Crear array 'all' combinando todas las categorías
const allWords = [
    ...categories.fiesta,
    ...categories.celebridades,
    ...categories.navidad,
    ...categories.comida,
    ...categories.hollywood,
    ...categories.marcas,
    ...categories.lugares,
    ...categories.animales,
    ...categories.deportes,
    ...categories.picante
];

categories.all = allWords;

function getRandomWord(category = 'all') {
    const categoryWords = categories[category];

    if (!categoryWords || categoryWords.length === 0) {
        console.error(`⚠️ Categoría vacía: ${category}`);
        return null;
    }

    const randomIndex = Math.floor(Math.random() * categoryWords.length);
    const selectedWord = categoryWords[randomIndex];

    return {
        word: selectedWord.word,
        hint: selectedWord.hint
    };
}

function generateRoomCode() {
    const characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
    let code = '';
    for (let i = 0; i < 6; i++) {
        code += characters.charAt(Math.floor(Math.random() * characters.length));
    }
    return code;
}

function selectImpostors(players, impostorCount) {
    const shuffled = [...players].sort(() => Math.random() - 0.5);
    const impostorIds = shuffled.slice(0, impostorCount).map(p => p.id);
    return impostorIds;
}

module.exports = {
    getRandomWord,
    generateRoomCode,
    selectImpostors,
    categories: Object.keys(categories).filter(key => key !== 'all')
};